apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "easydo.agentFullname" . }}
  labels:
    {{- include "easydo.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "easydo.agentFullname" . }}
  replicas: {{ .Values.agent.replicaCount }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      {{- include "easydo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "easydo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- with .Values.agent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: EASYDO_SERVER_URL
              value: {{ .Values.agent.env.serverURL | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AGENT_NAME
              value: "$(POD_NAME)"
          volumeMounts:
            - name: data
              mountPath: /data/agent
            {{- with .Values.agent.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with .Values.agent.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [{{ .Values.agent.persistence.accessMode | quote }}]
        {{- with .Values.agent.persistence.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.agent.persistence.size }}
