apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "easydo.agentFullname" . }}
  labels:
    {{- include "easydo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  selector:
    matchLabels:
      {{- include "easydo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: agent
  template:
    metadata:
      labels:
        {{- include "easydo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: agent
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          {{- with .Values.agent.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: EASYDO_SERVER_URL
              value: {{ .Values.agent.env.serverURL | quote }}
            - name: AGENT_NAME
              value: "{{ .Values.agent.env.namePrefix }}-$(POD_NAME)"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          {{- if or .Values.agent.mountDockerSock .Values.agent.extraVolumeMounts }}
          volumeMounts:
            {{- if .Values.agent.mountDockerSock }}
            - name: docker-sock
              mountPath: {{ .Values.agent.dockerSockPath | quote }}
            {{- end }}
            {{- with .Values.agent.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
      {{- if or .Values.agent.mountDockerSock .Values.agent.extraVolumes }}
      volumes:
        {{- if .Values.agent.mountDockerSock }}
        - name: docker-sock
          hostPath:
            path: {{ .Values.agent.dockerSockPath | quote }}
            type: Socket
        {{- end }}
        {{- with .Values.agent.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
