apiVersion: v1
kind: Service
metadata:
  name: {{ include "easydo.frontendFullname" . }}
  labels:
    {{- include "easydo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    {{- include "easydo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
