{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "easydo.mariadbFullname" . }}-config
  labels:
    {{- include "easydo.labels" . | nindent 4 }}
data:
  zz-easydo.cnf: |
    [mysqld]
    innodb_buffer_pool_size={{ .Values.mariadb.config.innodb_buffer_pool_size }}
    innodb_flush_log_at_trx_commit={{ .Values.mariadb.config.innodb_flush_log_at_trx_commit }}
    sync_binlog={{ .Values.mariadb.config.sync_binlog }}
    performance_schema={{ .Values.mariadb.config.performance_schema }}
    slow_query_log={{ .Values.mariadb.config.slow_query_log }}
    long_query_time={{ .Values.mariadb.config.long_query_time }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "easydo.mariadbFullname" . }}
spec:
  serviceName: {{ include "easydo.mariadbFullname" . }}
  replicas: 1
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  selector:
    matchLabels:
      {{- include "easydo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        {{- include "easydo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.mariadb.auth.rootPassword | quote }}
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.auth.database | quote }}
          ports:
            - containerPort: {{ .Values.mariadb.service.port }}
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: config
              mountPath: /etc/mysql/conf.d/zz-easydo.cnf
              subPath: zz-easydo.cnf
      volumes:
        - name: config
          configMap:
            name: {{ include "easydo.mariadbFullname" . }}-config
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [{{ .Values.mariadb.persistence.accessMode | quote }}]
        {{- with .Values.mariadb.persistence.storageClassName }}
        storageClassName: {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mariadb.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "easydo.mariadbFullname" . }}
spec:
  selector:
    {{- include "easydo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: {{ .Values.mariadb.service.port }}
{{- end }}
