apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easydo.runtimeSecretFullname" . }}
  labels:
    {{- include "easydo.labels" . | nindent 4 }}
type: Opaque
stringData:
  server-internal-token: {{ required "global.internalToken is required" .Values.global.internalToken | quote }}
  ai-runtime-internal-token: {{ required "global.internalToken is required" .Values.global.internalToken | quote }}
