CREATE TABLE `mcp_call_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `request_id` varchar(191) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `tool_name` varchar(128) NOT NULL,
  `operation_type` varchar(32) NOT NULL,
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` varchar(191) DEFAULT NULL,
  `client_name` varchar(128) DEFAULT NULL,
  `protocol` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `duration_ms` bigint NOT NULL DEFAULT '0',
  `input_summary` text,
  `output_summary` text,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` text,
  PRIMARY KEY (`id`),
  KEY `idx_mcp_call_audits_request_id` (`request_id`),
  KEY `idx_mcp_call_audits_user_id` (`user_id`),
  KEY `idx_mcp_call_audits_workspace_id` (`workspace_id`),
  KEY `idx_mcp_call_audits_tool_name` (`tool_name`),
  KEY `idx_mcp_call_audits_operation_type` (`operation_type`),
  KEY `idx_mcp_call_audits_target_type` (`target_type`),
  KEY `idx_mcp_call_audits_target_id` (`target_id`),
  KEY `idx_mcp_call_audits_protocol` (`protocol`),
  KEY `idx_mcp_call_audits_status` (`status`),
  KEY `idx_mcp_call_audits_error_code` (`error_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
