-- Flyway schema baseline for EasyDo

CREATE TABLE `agent_log_chunks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `agent_session_id` varchar(64) DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT '1',
  `seq` bigint NOT NULL,
  `stream` varchar(16) DEFAULT 'stdout',
  `chunk` longtext,
  `timestamp` bigint NOT NULL,
  `unique_key` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_agent_log_chunks_unique_key` (`unique_key`),
  KEY `idx_agent_log_chunks_agent_id` (`agent_id`),
  KEY `idx_agent_log_chunks_agent_session_id` (`agent_session_id`),
  KEY `idx_agent_log_chunks_task_id` (`task_id`),
  KEY `idx_agent_log_chunks_pipeline_run_id` (`pipeline_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_log_segments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT '1',
  `segment_no` bigint NOT NULL,
  `start_seq` bigint NOT NULL,
  `end_seq` bigint NOT NULL,
  `line_count` bigint DEFAULT '0',
  `object_key` varchar(512) NOT NULL,
  `object_bucket` varchar(128) NOT NULL,
  `object_size` bigint DEFAULT '0',
  `content_type` varchar(64) DEFAULT 'application/gzip',
  `checksum` varchar(128) DEFAULT NULL,
  `completed` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_attempt_segment` (`task_id`,`attempt`,`segment_no`),
  KEY `idx_agent_log_segments_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_log_segments_agent_id` (`agent_id`),
  KEY `idx_agent_log_segments_object_key` (`object_key`),
  KEY `idx_agent_log_segments_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_task_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `agent_session_id` varchar(64) DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT '1',
  `status` varchar(32) NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `exit_code` bigint DEFAULT '0',
  `duration_ms` bigint DEFAULT '0',
  `error_msg` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_attempt_idem` (`task_id`,`attempt`,`idempotency_key`),
  KEY `idx_agent_task_events_task_id` (`task_id`),
  KEY `idx_agent_task_events_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_task_events_agent_id` (`agent_id`),
  KEY `idx_agent_task_events_agent_session_id` (`agent_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `credential_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `action` varchar(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `actor_id` bigint unsigned DEFAULT NULL,
  `result` varchar(32) NOT NULL,
  `detail_json` text,
  PRIMARY KEY (`id`),
  KEY `idx_credential_events_actor_id` (`actor_id`),
  KEY `idx_credential_events_credential_id` (`credential_id`),
  KEY `idx_credential_events_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `credentials` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `category` varchar(32) DEFAULT NULL,
  `scope` varchar(32) DEFAULT 'personal',
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `encrypted_payload` longtext NOT NULL,
  `lock_state` varchar(32) NOT NULL DEFAULT 'unlocked',
  `status` varchar(32) DEFAULT 'active',
  `expires_at` bigint DEFAULT NULL,
  `used_count` bigint DEFAULT '0',
  `last_used_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_credentials_name` (`name`),
  KEY `idx_credentials_type` (`type`),
  KEY `idx_credentials_category` (`category`),
  KEY `idx_credentials_workspace_id` (`workspace_id`),
  KEY `idx_credentials_project_id` (`project_id`),
  KEY `idx_credentials_owner_id` (`owner_id`),
  KEY `idx_credentials_lock_state` (`lock_state`),
  KEY `idx_credentials_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `master_keys` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `key_material` text NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_master_keys_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pipeline_credential_refs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `pipeline_id` bigint unsigned NOT NULL,
  `node_id` varchar(64) DEFAULT NULL,
  `task_type` varchar(64) DEFAULT NULL,
  `credential_slot` varchar(64) DEFAULT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pipeline_credential_refs_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_credential_refs_node_id` (`node_id`),
  KEY `idx_pipeline_credential_refs_task_type` (`task_type`),
  KEY `idx_pipeline_credential_refs_credential_slot` (`credential_slot`),
  KEY `idx_pipeline_credential_refs_credential_id` (`credential_id`),
  CONSTRAINT `fk_pipeline_credential_refs_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `username` varchar(64) NOT NULL,
  `password` varchar(128) NOT NULL,
  `email` varchar(128) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `nickname` varchar(64) DEFAULT NULL,
  `avatar` varchar(256) DEFAULT NULL,
  `bio` text,
  `role` varchar(32) DEFAULT 'user',
  `status` varchar(32) DEFAULT 'active',
  `last_login_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_users_username` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `host` varchar(255) NOT NULL,
  `port` bigint NOT NULL,
  `token` varchar(256) NOT NULL,
  `register_key` varchar(256) DEFAULT NULL,
  `status` varchar(32) DEFAULT 'offline',
  `registration_status` varchar(32) DEFAULT 'pending',
  `max_concurrent_pipelines` bigint DEFAULT '10',
  `approved_at` bigint DEFAULT NULL,
  `approved_by` bigint unsigned DEFAULT NULL,
  `approved_remark` text,
  `labels` text,
  `tags` text,
  `version` varchar(32) DEFAULT NULL,
  `os` varchar(64) DEFAULT NULL,
  `arch` varchar(32) DEFAULT NULL,
  `cpu_cores` bigint DEFAULT NULL,
  `memory_total` bigint DEFAULT NULL,
  `disk_total` bigint DEFAULT NULL,
  `base_info` longtext,
  `base_info_collected_at` bigint DEFAULT NULL,
  `hostname` varchar(128) DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `last_heart_at` bigint DEFAULT NULL,
  `heartbeat_interval` bigint DEFAULT '10',
  `consecutive_success` bigint DEFAULT '0',
  `consecutive_failures` bigint DEFAULT '0',
  `scope_type` varchar(32) DEFAULT 'platform',
  `workspace_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agents_owner_id` (`owner_id`),
  KEY `idx_agents_approved_by` (`approved_by`),
  KEY `idx_agents_scope_type` (`scope_type`),
  KEY `idx_agents_workspace_id` (`workspace_id`),
  KEY `idx_agents_created_by` (`created_by`),
  CONSTRAINT `fk_agents_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_heartbeats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `timestamp` bigint NOT NULL,
  `cpu_usage` double DEFAULT NULL,
  `memory_usage` double DEFAULT NULL,
  `disk_usage` double DEFAULT NULL,
  `load_avg` varchar(64) DEFAULT NULL,
  `tasks_running` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_heartbeats_agent_id` (`agent_id`),
  CONSTRAINT `fk_agent_heartbeats_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `llm_model_catalogs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `source` varchar(32) NOT NULL,
  `source_model_id` varchar(255) NOT NULL,
  `parameter_size` varchar(64) DEFAULT NULL,
  `summary` text,
  `license` varchar(128) DEFAULT NULL,
  `tags` longtext,
  `metadata` longtext,
  `imported_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_llm_model_catalogs_name` (`name`),
  KEY `idx_llm_model_catalog_source_ref` (`source`,`source_model_id`),
  KEY `idx_llm_model_catalogs_imported_by` (`imported_by`),
  CONSTRAINT `fk_llm_model_catalogs_importer` FOREIGN KEY (`imported_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `notification_id` bigint unsigned DEFAULT NULL,
  `event_id` bigint unsigned DEFAULT NULL,
  `audience_id` bigint unsigned DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_id` bigint unsigned DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `event_type` varchar(64) DEFAULT NULL,
  `title` varchar(256) NOT NULL,
  `content` longtext,
  `sender_id` bigint unsigned DEFAULT NULL,
  `sender_type` varchar(32) DEFAULT 'system',
  `priority` bigint DEFAULT '0',
  `is_read` tinyint(1) DEFAULT '0',
  `read_at` bigint DEFAULT NULL,
  `metadata` text,
  `channel` varchar(32) DEFAULT 'in_app',
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_messages_notification_id` (`notification_id`),
  KEY `idx_messages_event_id` (`event_id`),
  KEY `idx_messages_audience_id` (`audience_id`),
  KEY `idx_messages_workspace_id` (`workspace_id`),
  KEY `idx_messages_recipient_id` (`recipient_id`),
  KEY `idx_messages_sender_id` (`sender_id`),
  KEY `idx_messages_resource_type` (`resource_type`),
  KEY `idx_messages_resource_id` (`resource_id`),
  CONSTRAINT `fk_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `webhook_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `secret` varchar(255) DEFAULT NULL,
  `events` text,
  `is_active` tinyint(1) DEFAULT '1',
  `created_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_webhook_configs_workspace_id` (`workspace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `webhook_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `config_id` bigint unsigned DEFAULT NULL,
  `event_type` varchar(50) DEFAULT NULL,
  `payload` text,
  `status` varchar(20) DEFAULT NULL,
  `response` text,
  `retry_count` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_webhook_events_workspace_id` (`workspace_id`),
  KEY `idx_webhook_events_config_id` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workspaces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `slug` varchar(128) NOT NULL,
  `description` text,
  `status` varchar(32) DEFAULT 'active',
  `visibility` varchar(32) DEFAULT 'private',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspaces_slug` (`slug`),
  KEY `idx_workspaces_status` (`status`),
  KEY `idx_workspaces_created_by` (`created_by`),
  CONSTRAINT `fk_workspaces_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `projects` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) NOT NULL,
  `description` text,
  `color` varchar(20) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `is_favorited` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_project_name` (`name`,`workspace_id`),
  KEY `idx_projects_workspace_id` (`workspace_id`),
  KEY `idx_projects_owner_id` (`owner_id`),
  CONSTRAINT `fk_projects_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_users_projects` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext,
  `priority` bigint DEFAULT '0',
  `metadata` longtext,
  `idempotency_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_events_idempotency_key` (`idempotency_key`),
  KEY `idx_notification_events_workspace_id` (`workspace_id`),
  KEY `idx_notification_events_family` (`family`),
  KEY `idx_notification_events_resource_type` (`resource_type`),
  KEY `idx_notification_events_resource_id` (`resource_id`),
  KEY `idx_notification_events_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notification_events_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notification_events_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_audiences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `permission_policy` varchar(64) DEFAULT 'workspace_member',
  `audience_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_audiences_audience_key` (`audience_key`),
  KEY `idx_notification_audiences_event_id` (`event_id`),
  KEY `idx_notification_audiences_workspace_id` (`workspace_id`),
  KEY `idx_notification_audiences_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notification_audiences_resource_type` (`resource_type`),
  KEY `idx_notification_audiences_resource_id` (`resource_id`),
  CONSTRAINT `fk_notification_audiences_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notification_audiences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notification_audiences_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `audience_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext,
  `priority` bigint DEFAULT '0',
  `metadata` longtext,
  `canonical_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notifications_canonical_key` (`canonical_key`),
  KEY `idx_notifications_event_id` (`event_id`),
  KEY `idx_notifications_audience_id` (`audience_id`),
  KEY `idx_notifications_workspace_id` (`workspace_id`),
  KEY `idx_notifications_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notifications_family` (`family`),
  KEY `idx_notifications_resource_type` (`resource_type`),
  KEY `idx_notifications_resource_id` (`resource_id`),
  KEY `idx_notifications_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notifications_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notifications_audience` FOREIGN KEY (`audience_id`) REFERENCES `notification_audiences` (`id`),
  CONSTRAINT `fk_notifications_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notifications_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notifications_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_deliveries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `notification_id` bigint unsigned NOT NULL,
  `channel` varchar(32) NOT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `provider` varchar(64) DEFAULT NULL,
  `external_ref` varchar(191) DEFAULT NULL,
  `error_message` text,
  `attempt_count` bigint NOT NULL DEFAULT '0',
  `last_attempt_at` bigint DEFAULT NULL,
  `next_retry_at` bigint DEFAULT NULL,
  `sent_at` bigint DEFAULT NULL,
  `read_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_delivery_channel` (`notification_id`,`channel`),
  KEY `idx_notification_deliveries_status` (`status`),
  KEY `idx_notification_deliveries_next_retry_at` (`next_retry_at`),
  CONSTRAINT `fk_notification_deliveries_notification` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_preferences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `user_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `channel` varchar(32) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `rule_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_preferences_rule_key` (`rule_key`),
  KEY `idx_notification_preferences_user_id` (`user_id`),
  KEY `idx_notification_preferences_workspace_id` (`workspace_id`),
  KEY `idx_notification_preferences_resource_type` (`resource_type`),
  KEY `idx_notification_preferences_resource_id` (`resource_id`),
  KEY `idx_notification_preferences_family` (`family`),
  KEY `idx_notification_preferences_event_type` (`event_type`),
  KEY `idx_notification_preferences_channel` (`channel`),
  CONSTRAINT `fk_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notification_preferences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pipelines` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `config` longtext,
  `definition_json` longtext,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `environment` varchar(32) DEFAULT 'development',
  `is_public` tinyint(1) DEFAULT '0',
  `is_favorite` tinyint(1) DEFAULT '0',
  `management_hidden` tinyint(1) DEFAULT '0',
  `version` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_pipelines_workspace_id` (`workspace_id`),
  KEY `idx_pipelines_project_id` (`project_id`),
  KEY `idx_pipelines_owner_id` (`owner_id`),
  KEY `idx_pipelines_management_hidden` (`management_hidden`),
  CONSTRAINT `fk_pipelines_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_projects_pipelines` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_users_pipelines` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `deploy_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `project_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `deployer_id` bigint unsigned DEFAULT NULL,
  `app_name` varchar(64) NOT NULL,
  `version` varchar(64) NOT NULL,
  `environment` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `deploy_type` varchar(32) DEFAULT NULL,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deploy_records_project_id` (`project_id`),
  KEY `idx_deploy_records_pipeline_id` (`pipeline_id`),
  KEY `idx_deploy_records_deployer_id` (`deployer_id`),
  CONSTRAINT `fk_deploy_records_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`),
  CONSTRAINT `fk_projects_deploy_records` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_users_deploy_records` FOREIGN KEY (`deployer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pipeline_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned NOT NULL,
  `build_number` bigint NOT NULL,
  `status` varchar(32) NOT NULL,
  `trigger_type` varchar(32) DEFAULT NULL,
  `trigger_user` varchar(64) DEFAULT NULL,
  `trigger_user_id` bigint unsigned DEFAULT '0',
  `trigger_user_role` varchar(32) DEFAULT NULL,
  `trigger_source` varchar(256) DEFAULT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `error_msg` text,
  `config` longtext,
  `run_config_json` longtext,
  `pipeline_snapshot_json` longtext,
  `resolved_nodes_json` longtext,
  `outputs_json` longtext,
  `bindings_snapshot_json` longtext,
  `events_json` longtext,
  `agent_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pipeline_build_number` (`pipeline_id`,`build_number`),
  UNIQUE KEY `idx_pipeline_runs_idempotency_key` (`idempotency_key`),
  KEY `idx_pipeline_runs_workspace_id` (`workspace_id`),
  KEY `idx_pipeline_runs_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_runs_trigger_user_id` (`trigger_user_id`),
  KEY `idx_pipeline_runs_agent_id` (`agent_id`),
  CONSTRAINT `fk_pipeline_runs_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_pipelines_runs` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `node_id` varchar(128) DEFAULT NULL,
  `task_type` varchar(64) NOT NULL,
  `name` varchar(256) DEFAULT NULL,
  `params` longtext,
  `script` longtext,
  `work_dir` varchar(512) DEFAULT NULL,
  `env_vars` text,
  `status` varchar(32) DEFAULT 'queued',
  `dispatch_token` varchar(64) DEFAULT NULL,
  `dispatch_attempt` bigint DEFAULT '0',
  `lease_expire_at` bigint DEFAULT '0',
  `agent_session_id` varchar(64) DEFAULT NULL,
  `owner_server_id` varchar(128) DEFAULT NULL,
  `priority` bigint DEFAULT '0',
  `timeout` bigint DEFAULT '3600',
  `retry_count` bigint DEFAULT '0',
  `max_retries` bigint DEFAULT '3',
  `exit_code` bigint DEFAULT '0',
  `error_msg` text,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `result_data` longtext,
  `repo_url` varchar(512) DEFAULT NULL,
  `repo_branch` varchar(128) DEFAULT NULL,
  `repo_commit` varchar(64) DEFAULT NULL,
  `repo_path` varchar(512) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_run_node` (`pipeline_run_id`,`node_id`),
  KEY `idx_agent_tasks_agent_session_id` (`agent_session_id`),
  KEY `idx_agent_tasks_node_id` (`node_id`),
  KEY `idx_agent_tasks_lease_expire_at` (`lease_expire_at`),
  KEY `idx_agent_tasks_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_tasks_status` (`status`),
  KEY `idx_agent_tasks_dispatch_token` (`dispatch_token`),
  KEY `idx_agent_tasks_owner_server_id` (`owner_server_id`),
  KEY `idx_agent_tasks_created_by` (`created_by`),
  KEY `idx_agent_tasks_workspace_id` (`workspace_id`),
  KEY `idx_agent_tasks_agent_id` (`agent_id`),
  CONSTRAINT `fk_agent_tasks_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`),
  CONSTRAINT `fk_pipeline_runs_tasks` FOREIGN KEY (`pipeline_run_id`) REFERENCES `pipeline_runs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `agent_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned DEFAULT '0',
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `level` varchar(16) DEFAULT 'info',
  `message` longtext,
  `timestamp` bigint NOT NULL,
  `source` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_logs_task_id` (`task_id`),
  KEY `idx_agent_logs_pipeline_run_id` (`pipeline_run_id`),
  CONSTRAINT `fk_agent_tasks_logs` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `pipeline_triggers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned NOT NULL,
  `provider` varchar(32) NOT NULL DEFAULT 'gitlab',
  `webhook_enabled` tinyint(1) DEFAULT '0',
  `push_enabled` tinyint(1) DEFAULT '0',
  `tag_enabled` tinyint(1) DEFAULT '0',
  `merge_request_enabled` tinyint(1) DEFAULT '0',
  `schedule_enabled` tinyint(1) DEFAULT '0',
  `cron_expression` varchar(128) DEFAULT NULL,
  `timezone` varchar(64) DEFAULT 'UTC',
  `push_branch_filters` text,
  `tag_filters` text,
  `merge_request_source_branch_filters` text,
  `merge_request_target_branch_filters` text,
  `secret_token` varchar(255) DEFAULT NULL,
  `webhook_token` varchar(255) DEFAULT NULL,
  `last_event_types` text,
  `next_run_at` datetime(3) DEFAULT NULL,
  `last_run_at` datetime(3) DEFAULT NULL,
  `last_triggered_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pipeline_trigger_pipeline` (`workspace_id`,`pipeline_id`),
  KEY `idx_pipeline_triggers_updated_by` (`updated_by`),
  KEY `idx_pipeline_triggers_workspace_id` (`workspace_id`),
  KEY `idx_pipeline_triggers_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_triggers_webhook_token` (`webhook_token`),
  KEY `idx_pipeline_triggers_created_by` (`created_by`),
  CONSTRAINT `fk_pipeline_triggers_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `type` varchar(32) NOT NULL,
  `environment` varchar(32) DEFAULT 'development',
  `status` varchar(32) DEFAULT 'offline',
  `endpoint` varchar(512) DEFAULT NULL,
  `labels` longtext,
  `metadata` longtext,
  `base_info` longtext,
  `base_info_status` varchar(32) DEFAULT '',
  `base_info_source` varchar(64) DEFAULT NULL,
  `base_info_last_error` text,
  `base_info_collected_at` bigint DEFAULT NULL,
  `last_check_at` bigint DEFAULT NULL,
  `last_check_result` text,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resources_name` (`name`),
  KEY `idx_resources_type` (`type`),
  KEY `idx_resources_environment` (`environment`),
  KEY `idx_resources_status` (`status`),
  KEY `idx_resources_base_info_status` (`base_info_status`),
  KEY `idx_resources_created_by` (`created_by`),
  KEY `idx_resources_workspace_id` (`workspace_id`),
  KEY `idx_resources_project_id` (`project_id`),
  CONSTRAINT `fk_resources_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resources_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_resources_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_credential_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `purpose` varchar(64) DEFAULT 'primary',
  `bound_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resource_credential_bindings_workspace_id` (`workspace_id`),
  KEY `idx_resource_credential_bindings_resource_id` (`resource_id`),
  KEY `idx_resource_credential_bindings_credential_id` (`credential_id`),
  KEY `idx_resource_credential_bindings_bound_by` (`bound_by`),
  CONSTRAINT `fk_resource_credential_bindings_binder` FOREIGN KEY (`bound_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_credential_bindings_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_resources_bindings` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_health_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL,
  `summary` text,
  `metrics` longtext,
  `observed_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resource_health_snapshots_workspace_id` (`workspace_id`),
  KEY `idx_resource_health_snapshots_resource_id` (`resource_id`),
  KEY `idx_resource_health_snapshots_status` (`status`),
  KEY `idx_resource_health_snapshots_observed_at` (`observed_at`),
  CONSTRAINT `fk_resources_health` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_terminal_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `session_id` varchar(64) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `endpoint` varchar(512) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `owner_server_id` varchar(128) DEFAULT NULL,
  `owner_connection_id` varchar(64) DEFAULT NULL,
  `attached_by` bigint unsigned DEFAULT NULL,
  `attached_at` bigint DEFAULT NULL,
  `close_reason` varchar(128) DEFAULT NULL,
  `closed_at` bigint DEFAULT NULL,
  `closed_by` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_resource_terminal_sessions_session_id` (`session_id`),
  KEY `idx_resource_terminal_sessions_workspace_id` (`workspace_id`),
  KEY `idx_resource_terminal_sessions_resource_id` (`resource_id`),
  KEY `idx_resource_terminal_sessions_credential_id` (`credential_id`),
  KEY `idx_resource_terminal_sessions_agent_id` (`agent_id`),
  KEY `idx_resource_terminal_sessions_resource_type` (`resource_type`),
  KEY `idx_resource_terminal_sessions_status` (`status`),
  KEY `idx_resource_terminal_sessions_owner_server_id` (`owner_server_id`),
  KEY `idx_resource_terminal_sessions_owner_connection_id` (`owner_connection_id`),
  KEY `idx_resource_terminal_sessions_attached_by` (`attached_by`),
  KEY `idx_resource_terminal_sessions_closed_by` (`closed_by`),
  KEY `idx_resource_terminal_sessions_created_by` (`created_by`),
  CONSTRAINT `fk_resource_terminal_sessions_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_resource` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_attacher` FOREIGN KEY (`attached_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_closer` FOREIGN KEY (`closed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `resource_operation_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `domain` varchar(32) NOT NULL,
  `namespace` varchar(128) DEFAULT NULL,
  `target_kind` varchar(64) DEFAULT NULL,
  `target_name` varchar(255) DEFAULT NULL,
  `action` varchar(64) NOT NULL,
  `reason` text,
  `request_snapshot` longtext,
  `result_summary` text,
  `error_message` text,
  `task_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'queued',
  `created_by` bigint unsigned NOT NULL,
  `completed_at` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_resource_operation_audits_workspace_id` (`workspace_id`),
  KEY `idx_resource_operation_audits_resource_id` (`resource_id`),
  KEY `idx_resource_operation_audits_resource_type` (`resource_type`),
  KEY `idx_resource_operation_audits_domain` (`domain`),
  KEY `idx_resource_operation_audits_namespace` (`namespace`),
  KEY `idx_resource_operation_audits_target_kind` (`target_kind`),
  KEY `idx_resource_operation_audits_target_name` (`target_name`),
  KEY `idx_resource_operation_audits_action` (`action`),
  KEY `idx_resource_operation_audits_task_id` (`task_id`),
  KEY `idx_resource_operation_audits_status` (`status`),
  KEY `idx_resource_operation_audits_created_by` (`created_by`),
  KEY `idx_resource_operation_audits_completed_at` (`completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `category` varchar(64) DEFAULT NULL,
  `template_type` varchar(32) NOT NULL,
  `target_resource_type` varchar(32) NOT NULL,
  `source` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `summary` varchar(512) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_store_templates_created_by` (`created_by`),
  KEY `idx_store_templates_workspace_id` (`workspace_id`),
  KEY `idx_store_templates_name` (`name`),
  KEY `idx_store_templates_category` (`category`),
  KEY `idx_store_templates_template_type` (`template_type`),
  KEY `idx_store_templates_target_resource_type` (`target_resource_type`),
  KEY `idx_store_templates_source` (`source`),
  KEY `idx_store_templates_status` (`status`),
  CONSTRAINT `fk_store_templates_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_store_templates_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `store_template_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `template_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `version` varchar(64) NOT NULL,
  `deployment_mode` varchar(64) NOT NULL,
  `default_config` longtext,
  `dependency_config` longtext,
  `target_constraints` longtext,
  `status` varchar(32) NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_store_template_versions_created_by` (`created_by`),
  KEY `idx_store_template_versions_workspace_id` (`workspace_id`),
  KEY `idx_store_template_versions_template_id` (`template_id`),
  KEY `idx_store_template_versions_pipeline_id` (`pipeline_id`),
  KEY `idx_store_template_versions_version` (`version`),
  KEY `idx_store_template_versions_status` (`status`),
  CONSTRAINT `fk_store_template_versions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_store_template_versions_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`),
  CONSTRAINT `fk_store_templates_versions` FOREIGN KEY (`template_id`) REFERENCES `store_templates` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `deployment_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `template_id` bigint unsigned NOT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `template_type` varchar(32) NOT NULL,
  `target_resource_id` bigint unsigned NOT NULL,
  `target_resource_type` varchar(32) NOT NULL,
  `parameter_snapshot` longtext,
  `resource_snapshot` longtext,
  `template_version_snapshot` longtext,
  `llm_model_id` bigint unsigned DEFAULT NULL,
  `llm_model_snapshot` longtext,
  `validation_error` text,
  `status` varchar(32) NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `requested_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deployment_requests_template_type` (`template_type`),
  KEY `idx_deployment_requests_target_resource_type` (`target_resource_type`),
  KEY `idx_deployment_requests_llm_model_id` (`llm_model_id`),
  KEY `idx_deployment_requests_status` (`status`),
  KEY `idx_deployment_requests_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_deployment_requests_template_id` (`template_id`),
  KEY `idx_deployment_requests_template_version_id` (`template_version_id`),
  KEY `idx_deployment_requests_target_resource_id` (`target_resource_id`),
  KEY `idx_deployment_requests_pipeline_id` (`pipeline_id`),
  KEY `idx_deployment_requests_requested_by` (`requested_by`),
  KEY `idx_deployment_requests_workspace_id` (`workspace_id`),
  KEY `idx_deployment_requests_project_id` (`project_id`),
  CONSTRAINT `fk_deployment_requests_llm_model` FOREIGN KEY (`llm_model_id`) REFERENCES `llm_model_catalogs` (`id`),
  CONSTRAINT `fk_deployment_requests_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_deployment_requests_requester` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_deployment_requests_target_resource` FOREIGN KEY (`target_resource_id`) REFERENCES `resources` (`id`),
  CONSTRAINT `fk_deployment_requests_template` FOREIGN KEY (`template_id`) REFERENCES `store_templates` (`id`),
  CONSTRAINT `fk_deployment_requests_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `store_template_versions` (`id`),
  CONSTRAINT `fk_deployment_requests_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `deployment_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `request_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `log_path` varchar(512) DEFAULT NULL,
  `audit_summary` text,
  `result_summary` text,
  `effect_snapshot` longtext,
  `retry_count` bigint DEFAULT '0',
  `failure_reason` text,
  `execution_task_ref` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deployment_records_workspace_id` (`workspace_id`),
  KEY `idx_deployment_records_request_id` (`request_id`),
  KEY `idx_deployment_records_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_deployment_records_status` (`status`),
  CONSTRAINT `fk_deployment_requests_records` FOREIGN KEY (`request_id`) REFERENCES `deployment_requests` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `task_executions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `attempt` bigint NOT NULL,
  `status` varchar(32) DEFAULT 'assigned',
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `exit_code` bigint DEFAULT '0',
  `stdout` longtext,
  `stderr` longtext,
  `error_msg` text,
  PRIMARY KEY (`id`),
  KEY `idx_task_executions_task_id` (`task_id`),
  CONSTRAINT `fk_agent_tasks_executions` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `template_parameters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `label` varchar(128) NOT NULL,
  `description` text,
  `extra_tip` text NULL,
  `type` varchar(32) NOT NULL,
  `default_value` text,
  `option_values` longtext,
  `required` tinyint(1) DEFAULT '0',
  `mutable` tinyint(1) DEFAULT '1',
  `advanced` tinyint(1) DEFAULT '0',
  `sort_order` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_template_parameters_template_version_id` (`template_version_id`),
  CONSTRAINT `fk_store_template_versions_parameters` FOREIGN KEY (`template_version_id`) REFERENCES `store_template_versions` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=280 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workspace_invitations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `email` varchar(128) NOT NULL,
  `invited_user_id` bigint unsigned DEFAULT NULL,
  `role` varchar(32) DEFAULT 'viewer',
  `token_hash` varchar(128) NOT NULL,
  `status` varchar(32) DEFAULT 'pending',
  `invited_by` bigint unsigned NOT NULL,
  `expires_at` bigint DEFAULT NULL,
  `accepted_at` bigint DEFAULT NULL,
  `accepted_by_user` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_invitations_token_hash` (`token_hash`),
  KEY `idx_workspace_invitations_email` (`email`),
  KEY `idx_workspace_invitations_invited_user_id` (`invited_user_id`),
  KEY `idx_workspace_invitations_status` (`status`),
  KEY `idx_workspace_invitations_invited_by` (`invited_by`),
  KEY `idx_workspace_invitations_expires_at` (`expires_at`),
  KEY `idx_workspace_invitations_accepted_by_user` (`accepted_by_user`),
  KEY `idx_workspace_invitations_workspace_id` (`workspace_id`),
  CONSTRAINT `fk_workspace_invitations_accepted_by_user_ref` FOREIGN KEY (`accepted_by_user`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_invited_user` FOREIGN KEY (`invited_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_inviter` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workspace_members` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role` varchar(32) DEFAULT 'viewer',
  `status` varchar(32) DEFAULT 'active',
  `invited_by` bigint unsigned DEFAULT NULL,
  `joined_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_user` (`workspace_id`,`user_id`),
  KEY `idx_workspace_members_role` (`role`),
  KEY `idx_workspace_members_status` (`status`),
  KEY `idx_workspace_members_invited_by` (`invited_by`),
  KEY `fk_users_workspace_members` (`user_id`),
  CONSTRAINT `fk_users_workspace_members` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_members_inviter` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspaces_members` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
