-- EasyDo compacted schema baseline.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER DATABASE CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `agent_heartbeats` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `timestamp` bigint NOT NULL,
  `cpu_usage` double DEFAULT NULL,
  `memory_usage` double DEFAULT NULL,
  `disk_usage` double DEFAULT NULL,
  `load_avg` varchar(64) DEFAULT NULL,
  `tasks_running` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_heartbeats_agent_id` (`agent_id`),
  CONSTRAINT `fk_agent_heartbeats_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_log_chunks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `agent_session_id` varchar(64) DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT 1,
  `seq` bigint NOT NULL,
  `stream` varchar(16) DEFAULT 'stdout',
  `chunk` longtext DEFAULT NULL,
  `timestamp` bigint NOT NULL,
  `unique_key` varchar(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_agent_log_chunks_unique_key` (`unique_key`),
  KEY `idx_agent_log_chunks_agent_id` (`agent_id`),
  KEY `idx_agent_log_chunks_agent_session_id` (`agent_session_id`),
  KEY `idx_agent_log_chunks_task_id` (`task_id`),
  KEY `idx_agent_log_chunks_pipeline_run_id` (`pipeline_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_log_segments` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT 1,
  `segment_no` bigint NOT NULL,
  `start_seq` bigint NOT NULL,
  `end_seq` bigint NOT NULL,
  `line_count` bigint DEFAULT 0,
  `object_key` varchar(512) NOT NULL,
  `object_bucket` varchar(128) NOT NULL,
  `object_size` bigint DEFAULT 0,
  `content_type` varchar(64) DEFAULT 'application/gzip',
  `checksum` varchar(128) DEFAULT NULL,
  `completed` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_attempt_segment` (`task_id`,`attempt`,`segment_no`),
  KEY `idx_agent_log_segments_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_log_segments_agent_id` (`agent_id`),
  KEY `idx_agent_log_segments_object_key` (`object_key`),
  KEY `idx_agent_log_segments_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned DEFAULT 0,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `level` varchar(16) DEFAULT 'info',
  `message` longtext DEFAULT NULL,
  `timestamp` bigint NOT NULL,
  `source` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agent_logs_task_id` (`task_id`),
  KEY `idx_agent_logs_pipeline_run_id` (`pipeline_run_id`),
  CONSTRAINT `fk_agent_tasks_logs` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_task_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `agent_session_id` varchar(64) DEFAULT NULL,
  `attempt` bigint NOT NULL DEFAULT 1,
  `status` varchar(32) NOT NULL,
  `idempotency_key` varchar(128) NOT NULL,
  `exit_code` bigint DEFAULT 0,
  `duration_ms` bigint DEFAULT 0,
  `error_msg` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_attempt_idem` (`task_id`,`attempt`,`idempotency_key`),
  KEY `idx_agent_task_events_task_id` (`task_id`),
  KEY `idx_agent_task_events_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_task_events_agent_id` (`agent_id`),
  KEY `idx_agent_task_events_agent_session_id` (`agent_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agent_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `node_id` varchar(128) DEFAULT NULL,
  `task_type` varchar(64) NOT NULL,
  `name` varchar(256) DEFAULT NULL,
  `params` longtext DEFAULT NULL,
  `script` longtext DEFAULT NULL,
  `work_dir` varchar(512) DEFAULT NULL,
  `env_vars` text DEFAULT NULL,
  `status` varchar(32) DEFAULT 'queued',
  `dispatch_token` varchar(64) DEFAULT NULL,
  `dispatch_attempt` bigint DEFAULT 0,
  `lease_expire_at` bigint DEFAULT 0,
  `agent_session_id` varchar(64) DEFAULT NULL,
  `owner_server_id` varchar(128) DEFAULT NULL,
  `priority` bigint DEFAULT 0,
  `timeout` bigint DEFAULT 3600,
  `retry_count` bigint DEFAULT 0,
  `max_retries` bigint DEFAULT 3,
  `exit_code` bigint DEFAULT 0,
  `error_msg` text DEFAULT NULL,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `result_data` longtext DEFAULT NULL,
  `repo_url` varchar(512) DEFAULT NULL,
  `repo_branch` varchar(128) DEFAULT NULL,
  `repo_commit` varchar(64) DEFAULT NULL,
  `repo_path` varchar(512) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_task_run_node` (`pipeline_run_id`,`node_id`),
  KEY `idx_agent_tasks_agent_session_id` (`agent_session_id`),
  KEY `idx_agent_tasks_node_id` (`node_id`),
  KEY `idx_agent_tasks_lease_expire_at` (`lease_expire_at`),
  KEY `idx_agent_tasks_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_agent_tasks_status` (`status`),
  KEY `idx_agent_tasks_dispatch_token` (`dispatch_token`),
  KEY `idx_agent_tasks_owner_server_id` (`owner_server_id`),
  KEY `idx_agent_tasks_created_by` (`created_by`),
  KEY `idx_agent_tasks_workspace_id` (`workspace_id`),
  KEY `idx_agent_tasks_agent_id` (`agent_id`),
  CONSTRAINT `fk_agent_tasks_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`),
  CONSTRAINT `fk_pipeline_runs_tasks` FOREIGN KEY (`pipeline_run_id`) REFERENCES `pipeline_runs` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `agents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `host` varchar(255) NOT NULL,
  `port` bigint NOT NULL,
  `token` varchar(256) NOT NULL,
  `register_key` varchar(256) DEFAULT NULL,
  `status` varchar(32) DEFAULT 'offline',
  `registration_status` varchar(32) DEFAULT 'pending',
  `max_concurrent_pipelines` bigint DEFAULT 10,
  `task_concurrency` bigint NOT NULL DEFAULT 5,
  `dockerhub_mirrors` longtext DEFAULT NULL,
  `dockerhub_mirrors_configured` tinyint NOT NULL DEFAULT 0,
  `approved_at` bigint DEFAULT NULL,
  `approved_by` bigint unsigned DEFAULT NULL,
  `approved_remark` text DEFAULT NULL,
  `labels` text DEFAULT NULL,
  `tags` text DEFAULT NULL,
  `version` varchar(32) DEFAULT NULL,
  `os` varchar(64) DEFAULT NULL,
  `arch` varchar(32) DEFAULT NULL,
  `cpu_cores` bigint DEFAULT NULL,
  `memory_total` bigint DEFAULT NULL,
  `disk_total` bigint DEFAULT NULL,
  `base_info` longtext DEFAULT NULL,
  `base_info_collected_at` bigint DEFAULT NULL,
  `hostname` varchar(128) DEFAULT NULL,
  `ip_address` varchar(64) DEFAULT NULL,
  `last_heart_at` bigint DEFAULT NULL,
  `heartbeat_interval` bigint DEFAULT 10,
  `consecutive_success` bigint DEFAULT 0,
  `consecutive_failures` bigint DEFAULT 0,
  `scope_type` varchar(32) DEFAULT 'platform',
  `workspace_id` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_agents_owner_id` (`owner_id`),
  KEY `idx_agents_approved_by` (`approved_by`),
  KEY `idx_agents_scope_type` (`scope_type`),
  KEY `idx_agents_workspace_id` (`workspace_id`),
  KEY `idx_agents_created_by` (`created_by`),
  CONSTRAINT `fk_agents_owner` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ai_model_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `model_id` bigint unsigned NOT NULL,
  `provider_id` bigint unsigned NOT NULL,
  `provider_model_key` varchar(255) DEFAULT NULL,
  `settings_json` longtext DEFAULT NULL,
  `metadata_json` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `context_window_tokens` bigint unsigned DEFAULT NULL,
  `max_output_tokens` bigint unsigned DEFAULT NULL,
  `supports_tool_use` tinyint(1) NOT NULL DEFAULT 0,
  `supports_streaming` tinyint(1) NOT NULL DEFAULT 1,
  `capability_source` varchar(64) DEFAULT NULL,
  `capability_checked_at` datetime(3) DEFAULT NULL,
  `capability_snapshot_hash` varchar(71) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_model_bindings_workspace_id` (`workspace_id`),
  KEY `idx_ai_model_bindings_model_id` (`model_id`),
  KEY `idx_ai_model_bindings_provider_id` (`provider_id`),
  KEY `idx_ai_model_bindings_status` (`status`),
  KEY `idx_ai_model_bindings_created_by` (`created_by`),
  KEY `idx_ai_model_bindings_capability` (`workspace_id`, `capability_source`, `context_window_tokens`),
  CONSTRAINT `fk_ai_model_bindings_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_ai_model_bindings_model` FOREIGN KEY (`model_id`) REFERENCES `ai_model_catalogs` (`id`),
  CONSTRAINT `fk_ai_model_bindings_provider` FOREIGN KEY (`provider_id`) REFERENCES `ai_providers` (`id`),
  CONSTRAINT `fk_ai_model_bindings_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ai_model_catalogs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `display_name` varchar(255) DEFAULT NULL,
  `source` varchar(32) NOT NULL,
  `source_model_id` varchar(255) NOT NULL,
  `parameter_size` varchar(64) DEFAULT NULL,
  `context_window` bigint DEFAULT NULL,
  `summary` text DEFAULT NULL,
  `license` varchar(128) DEFAULT NULL,
  `tags` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL,
  `imported_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_model_catalogs_name` (`name`),
  KEY `idx_ai_model_catalog_source_ref` (`source`,`source_model_id`),
  KEY `idx_ai_model_catalogs_imported_by` (`imported_by`),
  CONSTRAINT `fk_ai_model_catalogs_importer` FOREIGN KEY (`imported_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `ai_providers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `provider_type` varchar(64) NOT NULL,
  `base_url` varchar(512) DEFAULT NULL,
  `credential_id` bigint unsigned DEFAULT NULL,
  `headers_json` longtext DEFAULT NULL,
  `settings_json` longtext DEFAULT NULL,
  `metadata_json` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_providers_workspace_id` (`workspace_id`),
  KEY `idx_ai_providers_name` (`name`),
  KEY `idx_ai_providers_provider_type` (`provider_type`),
  KEY `idx_ai_providers_status` (`status`),
  KEY `idx_ai_providers_credential_id` (`credential_id`),
  KEY `idx_ai_providers_created_by` (`created_by`),
  CONSTRAINT `fk_ai_providers_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_ai_providers_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_ai_providers_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `credential_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `action` varchar(64) NOT NULL,
  `actor_type` varchar(32) NOT NULL,
  `actor_id` bigint unsigned DEFAULT NULL,
  `result` varchar(32) NOT NULL,
  `detail_json` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_credential_events_actor_id` (`actor_id`),
  KEY `idx_credential_events_credential_id` (`credential_id`),
  KEY `idx_credential_events_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `credentials` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` varchar(512) DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `category` varchar(32) DEFAULT NULL,
  `scope` varchar(32) DEFAULT 'personal',
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `encrypted_payload` longtext NOT NULL,
  `lock_state` varchar(32) NOT NULL DEFAULT 'unlocked',
  `status` varchar(32) DEFAULT 'active',
  `expires_at` bigint DEFAULT NULL,
  `used_count` bigint DEFAULT 0,
  `last_used_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_credentials_name` (`name`),
  KEY `idx_credentials_type` (`type`),
  KEY `idx_credentials_category` (`category`),
  KEY `idx_credentials_workspace_id` (`workspace_id`),
  KEY `idx_credentials_project_id` (`project_id`),
  KEY `idx_credentials_owner_id` (`owner_id`),
  KEY `idx_credentials_lock_state` (`lock_state`),
  KEY `idx_credentials_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `deploy_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `project_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `deployer_id` bigint unsigned DEFAULT NULL,
  `app_name` varchar(64) NOT NULL,
  `version` varchar(64) NOT NULL,
  `environment` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `deploy_type` varchar(32) DEFAULT NULL,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deploy_records_project_id` (`project_id`),
  KEY `idx_deploy_records_pipeline_id` (`pipeline_id`),
  KEY `idx_deploy_records_deployer_id` (`deployer_id`),
  CONSTRAINT `fk_deploy_records_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`),
  CONSTRAINT `fk_projects_deploy_records` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_users_deploy_records` FOREIGN KEY (`deployer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `deployment_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `request_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `log_path` varchar(512) DEFAULT NULL,
  `audit_summary` text DEFAULT NULL,
  `result_summary` text DEFAULT NULL,
  `effect_snapshot` longtext DEFAULT NULL,
  `retry_count` bigint DEFAULT 0,
  `failure_reason` text DEFAULT NULL,
  `execution_task_ref` varchar(128) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deployment_records_workspace_id` (`workspace_id`),
  KEY `idx_deployment_records_request_id` (`request_id`),
  KEY `idx_deployment_records_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_deployment_records_status` (`status`),
  CONSTRAINT `fk_deployment_requests_records` FOREIGN KEY (`request_id`) REFERENCES `deployment_requests` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `deployment_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `template_id` bigint unsigned NOT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `template_type` varchar(32) NOT NULL,
  `target_resource_id` bigint unsigned NOT NULL,
  `target_resource_type` varchar(32) NOT NULL,
  `parameter_snapshot` longtext DEFAULT NULL,
  `resource_snapshot` longtext DEFAULT NULL,
  `template_version_snapshot` longtext DEFAULT NULL,
  `ai_model_id` bigint unsigned DEFAULT NULL,
  `ai_model_snapshot` longtext DEFAULT NULL,
  `validation_error` text DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `requested_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_deployment_requests_template_type` (`template_type`),
  KEY `idx_deployment_requests_target_resource_type` (`target_resource_type`),
  KEY `idx_deployment_requests_ai_model_id` (`ai_model_id`),
  KEY `idx_deployment_requests_status` (`status`),
  KEY `idx_deployment_requests_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_deployment_requests_template_id` (`template_id`),
  KEY `idx_deployment_requests_template_version_id` (`template_version_id`),
  KEY `idx_deployment_requests_target_resource_id` (`target_resource_id`),
  KEY `idx_deployment_requests_pipeline_id` (`pipeline_id`),
  KEY `idx_deployment_requests_requested_by` (`requested_by`),
  KEY `idx_deployment_requests_workspace_id` (`workspace_id`),
  KEY `idx_deployment_requests_project_id` (`project_id`),
  CONSTRAINT `fk_deployment_requests_ai_model` FOREIGN KEY (`ai_model_id`) REFERENCES `ai_model_catalogs` (`id`),
  CONSTRAINT `fk_deployment_requests_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_deployment_requests_requester` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_deployment_requests_target_resource` FOREIGN KEY (`target_resource_id`) REFERENCES `resources` (`id`),
  CONSTRAINT `fk_deployment_requests_template` FOREIGN KEY (`template_id`) REFERENCES `store_templates` (`id`),
  CONSTRAINT `fk_deployment_requests_template_version` FOREIGN KEY (`template_version_id`) REFERENCES `store_template_versions` (`id`),
  CONSTRAINT `fk_deployment_requests_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `master_keys` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `key_material` text NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_master_keys_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `mcp_call_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `request_id` varchar(191) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `tool_name` varchar(128) NOT NULL,
  `operation_type` varchar(32) NOT NULL,
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` varchar(191) DEFAULT NULL,
  `client_name` varchar(128) DEFAULT NULL,
  `protocol` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `duration_ms` bigint NOT NULL DEFAULT 0,
  `input_summary` text DEFAULT NULL,
  `output_summary` text DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_mcp_call_audits_request_id` (`request_id`),
  KEY `idx_mcp_call_audits_user_id` (`user_id`),
  KEY `idx_mcp_call_audits_workspace_id` (`workspace_id`),
  KEY `idx_mcp_call_audits_tool_name` (`tool_name`),
  KEY `idx_mcp_call_audits_operation_type` (`operation_type`),
  KEY `idx_mcp_call_audits_target_type` (`target_type`),
  KEY `idx_mcp_call_audits_target_id` (`target_id`),
  KEY `idx_mcp_call_audits_protocol` (`protocol`),
  KEY `idx_mcp_call_audits_status` (`status`),
  KEY `idx_mcp_call_audits_error_code` (`error_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `messages` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `notification_id` bigint unsigned DEFAULT NULL,
  `event_id` bigint unsigned DEFAULT NULL,
  `audience_id` bigint unsigned DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_id` bigint unsigned DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `event_type` varchar(64) DEFAULT NULL,
  `title` varchar(256) NOT NULL,
  `content` longtext DEFAULT NULL,
  `sender_id` bigint unsigned DEFAULT NULL,
  `sender_type` varchar(32) DEFAULT 'system',
  `priority` bigint DEFAULT 0,
  `is_read` tinyint DEFAULT 0,
  `read_at` bigint DEFAULT NULL,
  `metadata` text DEFAULT NULL,
  `channel` varchar(32) DEFAULT 'in_app',
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_messages_notification_id` (`notification_id`),
  KEY `idx_messages_event_id` (`event_id`),
  KEY `idx_messages_audience_id` (`audience_id`),
  KEY `idx_messages_workspace_id` (`workspace_id`),
  KEY `idx_messages_recipient_id` (`recipient_id`),
  KEY `idx_messages_sender_id` (`sender_id`),
  KEY `idx_messages_resource_type` (`resource_type`),
  KEY `idx_messages_resource_id` (`resource_id`),
  CONSTRAINT `fk_messages_sender` FOREIGN KEY (`sender_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notification_audiences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `permission_policy` varchar(64) DEFAULT 'workspace_member',
  `audience_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_audiences_audience_key` (`audience_key`),
  KEY `idx_notification_audiences_event_id` (`event_id`),
  KEY `idx_notification_audiences_workspace_id` (`workspace_id`),
  KEY `idx_notification_audiences_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notification_audiences_resource_type` (`resource_type`),
  KEY `idx_notification_audiences_resource_id` (`resource_id`),
  CONSTRAINT `fk_notification_audiences_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notification_audiences_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notification_audiences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notification_deliveries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `notification_id` bigint unsigned NOT NULL,
  `channel` varchar(32) NOT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `provider` varchar(64) DEFAULT NULL,
  `external_ref` varchar(191) DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `attempt_count` bigint NOT NULL DEFAULT 0,
  `last_attempt_at` bigint DEFAULT NULL,
  `next_retry_at` bigint DEFAULT NULL,
  `sent_at` bigint DEFAULT NULL,
  `read_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_delivery_channel` (`notification_id`,`channel`),
  KEY `idx_notification_deliveries_status` (`status`),
  KEY `idx_notification_deliveries_next_retry_at` (`next_retry_at`),
  CONSTRAINT `fk_notification_deliveries_notification` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notification_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext DEFAULT NULL,
  `priority` bigint DEFAULT 0,
  `metadata` longtext DEFAULT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_events_idempotency_key` (`idempotency_key`),
  KEY `idx_notification_events_workspace_id` (`workspace_id`),
  KEY `idx_notification_events_family` (`family`),
  KEY `idx_notification_events_resource_type` (`resource_type`),
  KEY `idx_notification_events_resource_id` (`resource_id`),
  KEY `idx_notification_events_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notification_events_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notification_events_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notification_preferences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `user_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `channel` varchar(32) NOT NULL,
  `enabled` tinyint NOT NULL DEFAULT 1,
  `rule_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_preferences_rule_key` (`rule_key`),
  KEY `idx_notification_preferences_user_id` (`user_id`),
  KEY `idx_notification_preferences_workspace_id` (`workspace_id`),
  KEY `idx_notification_preferences_resource_type` (`resource_type`),
  KEY `idx_notification_preferences_resource_id` (`resource_id`),
  KEY `idx_notification_preferences_family` (`family`),
  KEY `idx_notification_preferences_event_type` (`event_type`),
  KEY `idx_notification_preferences_channel` (`channel`),
  CONSTRAINT `fk_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notification_preferences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `audience_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext DEFAULT NULL,
  `priority` bigint DEFAULT 0,
  `metadata` longtext DEFAULT NULL,
  `canonical_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notifications_canonical_key` (`canonical_key`),
  KEY `idx_notifications_event_id` (`event_id`),
  KEY `idx_notifications_audience_id` (`audience_id`),
  KEY `idx_notifications_workspace_id` (`workspace_id`),
  KEY `idx_notifications_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notifications_family` (`family`),
  KEY `idx_notifications_resource_type` (`resource_type`),
  KEY `idx_notifications_resource_id` (`resource_id`),
  KEY `idx_notifications_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notifications_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notifications_audience` FOREIGN KEY (`audience_id`) REFERENCES `notification_audiences` (`id`),
  CONSTRAINT `fk_notifications_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notifications_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notifications_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pipeline_credential_refs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `pipeline_id` bigint unsigned NOT NULL,
  `node_id` varchar(64) DEFAULT NULL,
  `task_type` varchar(64) DEFAULT NULL,
  `credential_slot` varchar(64) DEFAULT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_pipeline_credential_refs_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_credential_refs_node_id` (`node_id`),
  KEY `idx_pipeline_credential_refs_task_type` (`task_type`),
  KEY `idx_pipeline_credential_refs_credential_slot` (`credential_slot`),
  KEY `idx_pipeline_credential_refs_credential_id` (`credential_id`),
  CONSTRAINT `fk_pipeline_credential_refs_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pipeline_runs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned NOT NULL,
  `build_number` bigint NOT NULL,
  `status` varchar(32) NOT NULL,
  `trigger_type` varchar(32) DEFAULT NULL,
  `trigger_user` varchar(64) DEFAULT NULL,
  `trigger_user_id` bigint unsigned DEFAULT 0,
  `trigger_user_role` varchar(32) DEFAULT NULL,
  `trigger_source` varchar(256) DEFAULT NULL,
  `idempotency_key` varchar(191) DEFAULT NULL,
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `timeout_seconds` bigint NOT NULL DEFAULT 0,
  `timeout_deadline` bigint NOT NULL DEFAULT 0,
  `error_msg` text DEFAULT NULL,
  `config` longtext DEFAULT NULL,
  `run_config_json` longtext DEFAULT NULL,
  `pipeline_snapshot_json` longtext DEFAULT NULL,
  `resolved_nodes_json` longtext DEFAULT NULL,
  `outputs_json` longtext DEFAULT NULL,
  `bindings_snapshot_json` longtext DEFAULT NULL,
  `events_json` longtext DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pipeline_build_number` (`pipeline_id`,`build_number`),
  UNIQUE KEY `idx_pipeline_runs_idempotency_key` (`idempotency_key`),
  KEY `idx_pipeline_runs_workspace_id` (`workspace_id`),
  KEY `idx_pipeline_runs_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_runs_trigger_user_id` (`trigger_user_id`),
  KEY `idx_pipeline_runs_agent_id` (`agent_id`),
  KEY `idx_pipeline_runs_timeout_deadline` (`status`,`timeout_deadline`),
  CONSTRAINT `fk_pipeline_runs_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_pipelines_runs` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pipeline_triggers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned NOT NULL,
  `provider` varchar(32) NOT NULL DEFAULT 'gitlab',
  `webhook_enabled` tinyint DEFAULT 0,
  `push_enabled` tinyint DEFAULT 0,
  `tag_enabled` tinyint DEFAULT 0,
  `merge_request_enabled` tinyint DEFAULT 0,
  `schedule_enabled` tinyint DEFAULT 0,
  `cron_expression` varchar(128) DEFAULT NULL,
  `timezone` varchar(64) DEFAULT 'UTC',
  `push_branch_filters` text DEFAULT NULL,
  `tag_filters` text DEFAULT NULL,
  `merge_request_source_branch_filters` text DEFAULT NULL,
  `merge_request_target_branch_filters` text DEFAULT NULL,
  `secret_token` varchar(255) DEFAULT NULL,
  `webhook_token` varchar(255) DEFAULT NULL,
  `last_event_types` text DEFAULT NULL,
  `webhook_runtime_input_mappings` longtext DEFAULT NULL,
  `webhook_config_status` varchar(32) NOT NULL DEFAULT 'valid',
  `webhook_config_invalid_reason` text DEFAULT NULL,
  `next_run_at` datetime(3) DEFAULT NULL,
  `last_run_at` datetime(3) DEFAULT NULL,
  `last_triggered_at` datetime(3) DEFAULT NULL,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_pipeline_trigger_pipeline` (`workspace_id`,`pipeline_id`),
  KEY `idx_pipeline_triggers_updated_by` (`updated_by`),
  KEY `idx_pipeline_triggers_workspace_id` (`workspace_id`),
  KEY `idx_pipeline_triggers_pipeline_id` (`pipeline_id`),
  KEY `idx_pipeline_triggers_webhook_token` (`webhook_token`),
  KEY `idx_pipeline_triggers_created_by` (`created_by`),
  CONSTRAINT `fk_pipeline_triggers_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `pipelines` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `config` longtext DEFAULT NULL,
  `definition_json` longtext DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `environment` varchar(32) DEFAULT 'development',
  `is_public` tinyint DEFAULT 0,
  `is_favorite` tinyint DEFAULT 0,
  `management_hidden` tinyint DEFAULT 0,
  `version` int NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `idx_pipelines_workspace_id` (`workspace_id`),
  KEY `idx_pipelines_project_id` (`project_id`),
  KEY `idx_pipelines_owner_id` (`owner_id`),
  KEY `idx_pipelines_management_hidden` (`management_hidden`),
  CONSTRAINT `fk_pipelines_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_projects_pipelines` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_users_pipelines` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `projects` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(64) NOT NULL,
  `description` text DEFAULT NULL,
  `color` varchar(20) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_id` bigint unsigned NOT NULL,
  `is_favorited` tinyint DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_project_name` (`name`,`workspace_id`),
  KEY `idx_projects_workspace_id` (`workspace_id`),
  KEY `idx_projects_owner_id` (`owner_id`),
  CONSTRAINT `fk_projects_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_users_projects` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resource_credential_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `purpose` varchar(64) DEFAULT 'primary',
  `bound_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resource_credential_bindings_workspace_id` (`workspace_id`),
  KEY `idx_resource_credential_bindings_resource_id` (`resource_id`),
  KEY `idx_resource_credential_bindings_credential_id` (`credential_id`),
  KEY `idx_resource_credential_bindings_bound_by` (`bound_by`),
  CONSTRAINT `fk_resource_credential_bindings_binder` FOREIGN KEY (`bound_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_credential_bindings_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_resources_bindings` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resource_health_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL,
  `summary` text DEFAULT NULL,
  `metrics` longtext DEFAULT NULL,
  `observed_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resource_health_snapshots_workspace_id` (`workspace_id`),
  KEY `idx_resource_health_snapshots_resource_id` (`resource_id`),
  KEY `idx_resource_health_snapshots_status` (`status`),
  KEY `idx_resource_health_snapshots_observed_at` (`observed_at`),
  CONSTRAINT `fk_resources_health` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resource_operation_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `domain` varchar(32) NOT NULL,
  `namespace` varchar(128) DEFAULT NULL,
  `target_kind` varchar(64) DEFAULT NULL,
  `target_name` varchar(255) DEFAULT NULL,
  `action` varchar(64) NOT NULL,
  `reason` text DEFAULT NULL,
  `request_snapshot` longtext DEFAULT NULL,
  `result_summary` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `task_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'queued',
  `created_by` bigint unsigned NOT NULL,
  `completed_at` bigint DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_resource_operation_audits_workspace_id` (`workspace_id`),
  KEY `idx_resource_operation_audits_resource_id` (`resource_id`),
  KEY `idx_resource_operation_audits_resource_type` (`resource_type`),
  KEY `idx_resource_operation_audits_domain` (`domain`),
  KEY `idx_resource_operation_audits_namespace` (`namespace`),
  KEY `idx_resource_operation_audits_target_kind` (`target_kind`),
  KEY `idx_resource_operation_audits_target_name` (`target_name`),
  KEY `idx_resource_operation_audits_action` (`action`),
  KEY `idx_resource_operation_audits_task_id` (`task_id`),
  KEY `idx_resource_operation_audits_status` (`status`),
  KEY `idx_resource_operation_audits_created_by` (`created_by`),
  KEY `idx_resource_operation_audits_completed_at` (`completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resource_runtime_labels` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `target_key` varchar(255) NOT NULL,
  `labels_json` longtext NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_resource_runtime_labels_target` (`workspace_id`,`resource_id`,`target_type`,`target_key`),
  KEY `idx_resource_runtime_labels_workspace_target` (`workspace_id`,`target_type`,`target_key`),
  KEY `idx_resource_runtime_labels_resource_target` (`resource_id`,`target_type`,`target_key`),
  KEY `idx_resource_runtime_labels_created_by` (`created_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resource_terminal_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `session_id` varchar(64) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `endpoint` varchar(512) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `owner_server_id` varchar(128) DEFAULT NULL,
  `owner_connection_id` varchar(64) DEFAULT NULL,
  `attached_by` bigint unsigned DEFAULT NULL,
  `attached_at` bigint DEFAULT NULL,
  `close_reason` varchar(128) DEFAULT NULL,
  `closed_at` bigint DEFAULT NULL,
  `closed_by` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_resource_terminal_sessions_session_id` (`session_id`),
  KEY `idx_resource_terminal_sessions_workspace_id` (`workspace_id`),
  KEY `idx_resource_terminal_sessions_resource_id` (`resource_id`),
  KEY `idx_resource_terminal_sessions_credential_id` (`credential_id`),
  KEY `idx_resource_terminal_sessions_agent_id` (`agent_id`),
  KEY `idx_resource_terminal_sessions_resource_type` (`resource_type`),
  KEY `idx_resource_terminal_sessions_status` (`status`),
  KEY `idx_resource_terminal_sessions_owner_server_id` (`owner_server_id`),
  KEY `idx_resource_terminal_sessions_owner_connection_id` (`owner_connection_id`),
  KEY `idx_resource_terminal_sessions_attached_by` (`attached_by`),
  KEY `idx_resource_terminal_sessions_closed_by` (`closed_by`),
  KEY `idx_resource_terminal_sessions_created_by` (`created_by`),
  CONSTRAINT `fk_resource_terminal_sessions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_attacher` FOREIGN KEY (`attached_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_closer` FOREIGN KEY (`closed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_resource` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `resources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `project_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `environment` varchar(32) DEFAULT 'development',
  `status` varchar(32) DEFAULT 'offline',
  `endpoint` varchar(512) DEFAULT NULL,
  `labels` longtext DEFAULT NULL,
  `metadata` longtext DEFAULT NULL,
  `base_info` longtext DEFAULT NULL,
  `base_info_status` varchar(32) DEFAULT '',
  `base_info_source` varchar(64) DEFAULT NULL,
  `base_info_last_error` text DEFAULT NULL,
  `base_info_collected_at` bigint DEFAULT NULL,
  `last_check_at` bigint DEFAULT NULL,
  `last_check_result` text DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_resources_name` (`name`),
  KEY `idx_resources_type` (`type`),
  KEY `idx_resources_environment` (`environment`),
  KEY `idx_resources_status` (`status`),
  KEY `idx_resources_base_info_status` (`base_info_status`),
  KEY `idx_resources_created_by` (`created_by`),
  KEY `idx_resources_workspace_id` (`workspace_id`),
  KEY `idx_resources_project_id` (`project_id`),
  CONSTRAINT `fk_resources_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resources_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `fk_resources_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `store_template_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `template_id` bigint unsigned NOT NULL,
  `pipeline_id` bigint unsigned DEFAULT NULL,
  `version` varchar(64) NOT NULL,
  `deployment_mode` varchar(64) NOT NULL,
  `default_config` longtext DEFAULT NULL,
  `dependency_config` longtext DEFAULT NULL,
  `target_constraints` longtext DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_store_template_versions_created_by` (`created_by`),
  KEY `idx_store_template_versions_workspace_id` (`workspace_id`),
  KEY `idx_store_template_versions_template_id` (`template_id`),
  KEY `idx_store_template_versions_pipeline_id` (`pipeline_id`),
  KEY `idx_store_template_versions_version` (`version`),
  KEY `idx_store_template_versions_status` (`status`),
  CONSTRAINT `fk_store_template_versions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_store_template_versions_pipeline` FOREIGN KEY (`pipeline_id`) REFERENCES `pipelines` (`id`),
  CONSTRAINT `fk_store_templates_versions` FOREIGN KEY (`template_id`) REFERENCES `store_templates` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `store_templates` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `category` varchar(64) DEFAULT NULL,
  `template_type` varchar(32) NOT NULL,
  `target_resource_type` varchar(32) NOT NULL,
  `source` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `summary` varchar(512) DEFAULT NULL,
  `icon` varchar(255) DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_store_templates_created_by` (`created_by`),
  KEY `idx_store_templates_workspace_id` (`workspace_id`),
  KEY `idx_store_templates_name` (`name`),
  KEY `idx_store_templates_category` (`category`),
  KEY `idx_store_templates_template_type` (`template_type`),
  KEY `idx_store_templates_target_resource_type` (`target_resource_type`),
  KEY `idx_store_templates_source` (`source`),
  KEY `idx_store_templates_status` (`status`),
  CONSTRAINT `fk_store_templates_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_store_templates_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `system_settings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `key` varchar(128) NOT NULL,
  `value` longtext DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_system_settings_key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `task_executions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `task_id` bigint unsigned NOT NULL,
  `attempt` bigint NOT NULL,
  `status` varchar(32) DEFAULT 'assigned',
  `start_time` bigint DEFAULT NULL,
  `end_time` bigint DEFAULT NULL,
  `duration` bigint DEFAULT NULL,
  `exit_code` bigint DEFAULT 0,
  `stdout` longtext DEFAULT NULL,
  `stderr` longtext DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_task_executions_task_id` (`task_id`),
  CONSTRAINT `fk_agent_tasks_executions` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `template_parameters` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `template_version_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `label` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `extra_tip` text DEFAULT NULL,
  `type` varchar(32) NOT NULL,
  `default_value` text DEFAULT NULL,
  `option_values` longtext DEFAULT NULL,
  `required` tinyint DEFAULT 0,
  `mutable` tinyint DEFAULT 1,
  `advanced` tinyint DEFAULT 0,
  `sort_order` bigint DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_template_parameters_template_version_id` (`template_version_id`),
  CONSTRAINT `fk_store_template_versions_parameters` FOREIGN KEY (`template_version_id`) REFERENCES `store_template_versions` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=280 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `username` varchar(64) NOT NULL,
  `password` varchar(128) NOT NULL,
  `email` varchar(128) NOT NULL,
  `phone` varchar(20) NOT NULL DEFAULT '',
  `phone_unique` varchar(20) GENERATED ALWAYS AS (NULLIF(`phone`, '')) VIRTUAL,
  `nickname` varchar(64) DEFAULT NULL,
  `avatar` varchar(256) DEFAULT NULL,
  `bio` text DEFAULT NULL,
  `role` varchar(32) DEFAULT 'user',
  `status` varchar(32) DEFAULT 'active',
  `last_login_at` bigint DEFAULT NULL,
  `must_change_password` tinyint(1) NOT NULL DEFAULT 0,
  `password_changed_at` bigint NOT NULL DEFAULT 0,
  `disabled_at` bigint NOT NULL DEFAULT 0,
  `disabled_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_users_username` (`username`),
  UNIQUE KEY `idx_users_email` (`email`),
  UNIQUE KEY `idx_users_phone` (`phone_unique`),
  KEY `idx_users_disabled_by` (`disabled_by`),
  CONSTRAINT `fk_users_disabled_by` FOREIGN KEY (`disabled_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `webhook_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `secret` varchar(255) DEFAULT NULL,
  `events` text DEFAULT NULL,
  `is_active` tinyint DEFAULT 1,
  `created_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_webhook_configs_workspace_id` (`workspace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `webhook_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `config_id` bigint unsigned DEFAULT NULL,
  `event_type` varchar(50) DEFAULT NULL,
  `payload` text DEFAULT NULL,
  `status` varchar(20) DEFAULT NULL,
  `response` text DEFAULT NULL,
  `retry_count` bigint DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_webhook_events_workspace_id` (`workspace_id`),
  KEY `idx_webhook_events_config_id` (`config_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `workspace_invitations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `email` varchar(128) NOT NULL,
  `invited_user_id` bigint unsigned DEFAULT NULL,
  `role` varchar(32) DEFAULT 'viewer',
  `token_hash` varchar(128) NOT NULL,
  `status` varchar(32) DEFAULT 'pending',
  `invited_by` bigint unsigned NOT NULL,
  `expires_at` bigint DEFAULT NULL,
  `accepted_at` bigint DEFAULT NULL,
  `accepted_by_user` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_invitations_token_hash` (`token_hash`),
  KEY `idx_workspace_invitations_email` (`email`),
  KEY `idx_workspace_invitations_invited_user_id` (`invited_user_id`),
  KEY `idx_workspace_invitations_status` (`status`),
  KEY `idx_workspace_invitations_invited_by` (`invited_by`),
  KEY `idx_workspace_invitations_expires_at` (`expires_at`),
  KEY `idx_workspace_invitations_accepted_by_user` (`accepted_by_user`),
  KEY `idx_workspace_invitations_workspace_id` (`workspace_id`),
  CONSTRAINT `fk_workspace_invitations_accepted_by_user_ref` FOREIGN KEY (`accepted_by_user`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_invited_user` FOREIGN KEY (`invited_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_inviter` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_invitations_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `workspace_members` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `role` varchar(32) DEFAULT 'viewer',
  `status` varchar(32) DEFAULT 'active',
  `invited_by` bigint unsigned DEFAULT NULL,
  `joined_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspace_user` (`workspace_id`,`user_id`),
  KEY `idx_workspace_members_role` (`role`),
  KEY `idx_workspace_members_status` (`status`),
  KEY `idx_workspace_members_invited_by` (`invited_by`),
  KEY `fk_users_workspace_members` (`user_id`),
  CONSTRAINT `fk_users_workspace_members` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspace_members_inviter` FOREIGN KEY (`invited_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_workspaces_members` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `workspaces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `slug` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `status` varchar(32) DEFAULT 'active',
  `visibility` varchar(32) DEFAULT 'private',
  `kind` varchar(32) NOT NULL DEFAULT 'normal',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_workspaces_slug` (`slug`),
  KEY `idx_workspaces_status` (`status`),
  KEY `idx_workspaces_created_by` (`created_by`),
  KEY `idx_workspaces_kind` (`kind`),
  CONSTRAINT `fk_workspaces_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;

-- Personnel management tables (final baseline)
CREATE TABLE `audit_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned NOT NULL,
  `actor_role` varchar(32) DEFAULT NULL,
  `actor_workspace_id` bigint unsigned DEFAULT NULL,
  `action` varchar(96) NOT NULL,
  `target_type` varchar(64) NOT NULL,
  `target_id` bigint unsigned NOT NULL,
  `before_json` longtext DEFAULT NULL,
  `after_json` longtext DEFAULT NULL,
  `metadata_json` longtext DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_audit_logs_workspace_id` (`workspace_id`),
  KEY `idx_audit_logs_actor_user_id` (`actor_user_id`),
  KEY `idx_audit_logs_actor_workspace_id` (`actor_workspace_id`),
  KEY `idx_audit_logs_action` (`action`),
  KEY `idx_audit_logs_target_type` (`target_type`),
  KEY `idx_audit_logs_target_id` (`target_id`),
  CONSTRAINT `fk_audit_logs_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_audit_logs_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_audit_logs_actor_workspace` FOREIGN KEY (`actor_workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `notification_sender_configs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `scope` varchar(32) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL DEFAULT 0,
  `enabled` tinyint(1) DEFAULT 0,
  `from_name` varchar(128) DEFAULT NULL,
  `from_address` varchar(255) DEFAULT NULL,
  `smtp_host` varchar(255) DEFAULT NULL,
  `smtp_port` bigint DEFAULT NULL,
  `smtp_username` varchar(255) DEFAULT NULL,
  `smtp_password_encrypted` longtext DEFAULT NULL,
  `smtp_tls_mode` varchar(32) DEFAULT 'plain',
  `updated_by` bigint unsigned DEFAULT NULL,
  `last_tested_at` bigint DEFAULT NULL,
  `last_test_status` varchar(32) DEFAULT NULL,
  `last_test_error` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_sender_scope_workspace` (`scope`,`workspace_id`),
  KEY `idx_notification_sender_configs_workspace_id` (`workspace_id`),
  KEY `idx_notification_sender_configs_updated_by` (`updated_by`),
  CONSTRAINT `fk_notification_sender_configs_updated_by` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- AI runtime schema (final baseline; intermediate ALTER history folded away)
CREATE TABLE `ai_runtime_sequences` (
  `name` varchar(96) NOT NULL,
  `next_value` bigint unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_profiles` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `profile_kind` varchar(64) NOT NULL DEFAULT 'generic',
  `context_tags_json` longtext NOT NULL,
  `provider_json` longtext NOT NULL,
  `binding_json` longtext NOT NULL,
  `model_json` longtext NOT NULL,
  `provider_credential_ref_json` longtext NOT NULL,
  `inference_json` longtext NOT NULL,
  `prompt_json` longtext NOT NULL,
  `context_contract_json` longtext NOT NULL,
  `input_schema_json` longtext NOT NULL,
  `output_schema_json` longtext NOT NULL,
  `tool_policy_json` longtext NOT NULL,
  `memory_policy_json` longtext NOT NULL,
  `confirmation_policy_json` longtext NOT NULL,
  `response_mode` varchar(32) NOT NULL DEFAULT 'text',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_profiles_workspace_name` (`workspace_id`,`name`),
  KEY `idx_ai_agent_profiles_workspace_status` (`workspace_id`,`status`),
  KEY `idx_ai_agent_profiles_workspace_kind` (`workspace_id`,`profile_kind`),
  KEY `idx_ai_agent_profiles_workspace_updated` (`workspace_id`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_profile_resource_refs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `profile_section` varchar(48) NOT NULL,
  `resource_type` varchar(64) NOT NULL,
  `resource_id` varchar(128) NOT NULL,
  `resource_id_kind` enum('database_id','resource_key') NOT NULL,
  `resource_version_id` bigint unsigned DEFAULT NULL,
  `resource_version` varchar(128) DEFAULT NULL,
  `snapshot_digest` varchar(96) DEFAULT NULL,
  `config_json` longtext NOT NULL,
  `required` tinyint NOT NULL DEFAULT 1,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_profile_resource_refs_profile` (`workspace_id`,`profile_id`,`profile_section`),
  KEY `idx_ai_profile_resource_refs_resource` (`workspace_id`,`resource_type`,`resource_id`),
  KEY `idx_ai_profile_resource_refs_version` (`workspace_id`,`resource_version_id`),
  CONSTRAINT `fk_ai_profile_resource_refs_profile` FOREIGN KEY (`profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_resources` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_kind` varchar(48) NOT NULL,
  `resource_key` varchar(128) NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `version` varchar(128) NOT NULL DEFAULT 'latest',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `spec_json` longtext NOT NULL,
  `endpoint_json` longtext NOT NULL,
  `secret_ref_json` longtext NOT NULL,
  `tags_json` longtext NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_resources_key` (`workspace_id`,`resource_kind`,`resource_key`),
  KEY `idx_ai_agent_resources_kind_status` (`workspace_id`,`resource_kind`,`status`),
  KEY `idx_ai_agent_resources_updated` (`workspace_id`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_profile_versions` (
  `id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `version` int unsigned NOT NULL,
  `snapshot_hash` varchar(96) NOT NULL,
  `snapshot_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'published',
  `published_by` bigint unsigned NOT NULL,
  `published_at` datetime(3) NOT NULL,
  `change_summary` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_profile_versions_profile_version` (`profile_id`,`version`),
  UNIQUE KEY `uk_ai_profile_versions_hash` (`workspace_id`,`snapshot_hash`),
  KEY `idx_ai_profile_versions_workspace_profile` (`workspace_id`,`profile_id`),
  CONSTRAINT `fk_ai_profile_versions_profile` FOREIGN KEY (`profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_profile_validation_results` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `profile_version_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `result_json` longtext NOT NULL,
  `validated_by` bigint unsigned NOT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_profile_validation_profile` (`workspace_id`,`profile_id`,`created_at`),
  KEY `idx_ai_profile_validation_version` (`workspace_id`,`profile_version_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `workspace_ai_settings` (
  `workspace_id` bigint unsigned NOT NULL,
  `settings_json` longtext NOT NULL,
  `updated_by` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`workspace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_runtime_workspaces` (
  `id` bigint unsigned NOT NULL,
  `workspace_runtime_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_user_id` bigint unsigned NOT NULL,
  `workspace_key` varchar(128) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `provider_endpoint` varchar(512) DEFAULT NULL,
  `sandbox_id` varchar(191) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `image` varchar(512) NOT NULL,
  `root_path` varchar(512) NOT NULL,
  `repository_json` longtext NOT NULL,
  `network_policy_json` longtext NOT NULL,
  `secret_refs_json` longtext NOT NULL,
  `quota_json` longtext NOT NULL,
  `snapshot_hash` varchar(96) NOT NULL,
  `lease_owner_instance_id` varchar(191) DEFAULT NULL,
  `lease_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `lease_expires_at` datetime(3) DEFAULT NULL,
  `provision_owner_instance_id` varchar(128) DEFAULT NULL,
  `provision_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `provision_expires_at` datetime(3) DEFAULT NULL,
  `state_version` bigint unsigned NOT NULL DEFAULT 0,
  `last_connected_at` datetime(3) DEFAULT NULL,
  `paused_at` datetime(3) DEFAULT NULL,
  `recycled_at` datetime(3) DEFAULT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_workspaces_runtime_id` (`workspace_runtime_id`),
  UNIQUE KEY `uk_ai_runtime_workspaces_owner_key` (`workspace_id`,`owner_user_id`,`workspace_key`),
  KEY `idx_ai_runtime_workspaces_owner_status` (`workspace_id`,`owner_user_id`,`status`,`updated_at`),
  KEY `idx_ai_runtime_workspaces_lease` (`status`,`lease_expires_at`),
  KEY `idx_ai_runtime_workspaces_provision` (`status`, `provision_expires_at`, `provision_owner_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_runtime_workspace_audits` (
  `audit_id` varchar(160) NOT NULL,
  `workspace_runtime_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_user_id` bigint unsigned NOT NULL,
  `actor_user_id` bigint unsigned NOT NULL,
  `operation` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `details_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`audit_id`),
  KEY `idx_ai_runtime_workspace_audits_workspace` (`workspace_id`,`workspace_runtime_id`,`created_at`),
  KEY `idx_ai_runtime_workspace_audits_actor` (`workspace_id`,`actor_user_id`,`created_at`),
  CONSTRAINT `fk_ai_runtime_workspace_audits_workspace` FOREIGN KEY (`workspace_runtime_id`) REFERENCES `ai_runtime_workspaces` (`workspace_runtime_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_sessions` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `session_kind` varchar(32) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `auth_session_id` varchar(128) NOT NULL,
  `business_type` varchar(64) DEFAULT NULL,
  `business_id` varchar(160) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `agent_profile_id` bigint unsigned NOT NULL,
  `agent_profile_version_id` bigint unsigned NOT NULL,
  `agent_profile_version_key` varchar(64) NOT NULL DEFAULT '',
  `agent_profile_snapshot_hash` varchar(96) NOT NULL,
  `agent_workspace_runtime_id` varchar(128) NOT NULL,
  `agent_workspace_snapshot_hash` varchar(96) NOT NULL,
  `session_key` varchar(512) DEFAULT NULL,
  `first_session_timestamp` datetime(3) DEFAULT NULL,
  `source` varchar(64) DEFAULT NULL,
  `model_override_json` longtext NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `title_source` varchar(32) NOT NULL DEFAULT 'fallback',
  `title_generated_at` datetime(3) DEFAULT NULL,
  `title_generation_error` text DEFAULT NULL,
  `entry_count` bigint unsigned NOT NULL DEFAULT 0,
  `last_entry_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_sessions_current` (`workspace_id`,`user_id`,`auth_session_id`,`session_kind`),
  KEY `idx_ai_sessions_business` (`workspace_id`,`business_type`,`business_id`),
  KEY `idx_ai_sessions_profile` (`workspace_id`,`agent_profile_id`,`agent_profile_version_id`),
  KEY `idx_ai_sessions_profile_key` (`workspace_id`,`agent_profile_id`,`agent_profile_version_key`,`status`,`updated_at`),
  KEY `idx_ai_sessions_session_key` (`workspace_id`,`session_key`),
  KEY `idx_ai_sessions_updated` (`workspace_id`,`updated_at`),
  CONSTRAINT `fk_ai_sessions_agent_profile` FOREIGN KEY (`agent_profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_session_entries` (
  `id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `parent_entry_id` bigint unsigned DEFAULT NULL,
  `seq` bigint unsigned NOT NULL,
  `entry_type` varchar(32) NOT NULL,
  `role` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `content` longtext DEFAULT NULL,
  `content_blocks_json` longtext NOT NULL,
  `input_json` longtext NOT NULL,
  `output_json` longtext NOT NULL,
  `runtime_run_id` varchar(64) DEFAULT NULL,
  `event_seq` bigint unsigned DEFAULT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_entries_seq` (`session_id`,`seq`),
  UNIQUE KEY `uk_ai_session_entries_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_session_entries_session` (`workspace_id`,`session_id`,`created_at`),
  KEY `idx_ai_session_entries_run` (`workspace_id`,`runtime_run_id`),
  CONSTRAINT `fk_ai_session_entries_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_current_sessions` (
  `session_key` varchar(512) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`session_key`),
  KEY `idx_ai_current_sessions_workspace` (`workspace_id`,`updated_at`),
  CONSTRAINT `fk_ai_current_sessions_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_runtime_runs` (
  `id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `agent_profile_id` bigint unsigned NOT NULL,
  `agent_profile_version_id` bigint unsigned NOT NULL,
  `agent_profile_version_key` varchar(64) NOT NULL DEFAULT '',
  `agent_profile_snapshot_hash` varchar(96) NOT NULL,
  `agent_workspace_runtime_id` varchar(128) NOT NULL,
  `agent_workspace_snapshot_hash` varchar(96) NOT NULL,
  `profile_snapshot_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL,
  `active_slot` varchar(16) DEFAULT NULL,
  `owner_instance_id` varchar(191) DEFAULT NULL,
  `owner_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `owner_lease_expires_at` datetime(3) DEFAULT NULL,
  `input_entry_id` bigint unsigned NOT NULL,
  `output_entry_id` bigint unsigned DEFAULT NULL,
  `request_json` longtext NOT NULL,
  `result_json` longtext NOT NULL,
  `usage_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_runs_run` (`runtime_run_id`),
  UNIQUE KEY `uk_ai_runtime_runs_active_root` (`workspace_id`,`session_id`,`active_slot`),
  KEY `idx_ai_runtime_runs_session` (`workspace_id`,`session_id`,`created_at`),
  KEY `idx_ai_runtime_runs_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_ai_runtime_runs_owner_lease` (`status`, `owner_lease_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_actions` (
  `id` bigint unsigned NOT NULL,
  `action_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `entry_id` bigint unsigned DEFAULT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_kind` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `source` varchar(32) NOT NULL,
  `capability_id` varchar(96) NOT NULL,
  `input_json` longtext NOT NULL,
  `input_digest` varchar(71) NOT NULL,
  `target_json` longtext NOT NULL,
  `policy_json` longtext NOT NULL,
  `display_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'awaiting_decision',
  `requested_by` bigint unsigned NOT NULL,
  `decided_by` bigint unsigned DEFAULT NULL,
  `decided_at` datetime(3) DEFAULT NULL,
  `executed_at` datetime(3) DEFAULT NULL,
  `result_json` longtext NOT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_actions_action_id` (`workspace_id`,`action_id`),
  UNIQUE KEY `uk_ai_agent_actions_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_agent_actions_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_ai_agent_actions_session` (`workspace_id`,`session_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_action_decisions` (
  `decision_id` varchar(160) NOT NULL,
  `decision_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `decision_type` varchar(32) NOT NULL,
  `decision` varchar(32) NOT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `input_patch_json` longtext NOT NULL,
  `client_decision_id` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`decision_id`),
  UNIQUE KEY `uk_ai_action_decisions_client` (`workspace_id`,`action_id`,`actor_user_id`,`client_decision_id`),
  UNIQUE KEY `uk_ai_action_decisions_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_action_decisions_action` (`workspace_id`,`action_id`,`decision_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_session_permission_grants` (
  `grant_id` varchar(160) NOT NULL,
  `grant_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `permission_key` varchar(160) NOT NULL,
  `tool_name` varchar(128) NOT NULL,
  `executor_type` varchar(32) NOT NULL,
  `resource_type` varchar(96) NOT NULL,
  `resource_id` varchar(160) NOT NULL,
  `status` varchar(32) NOT NULL,
  `granted_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`grant_id`),
  UNIQUE KEY `uk_ai_session_permission_grants_id` (`workspace_id`,`grant_id`),
  KEY `idx_ai_session_permission_grants_session` (`workspace_id`,`session_id`,`status`,`expires_at`),
  KEY `idx_ai_session_permission_grants_match` (`workspace_id`,`session_id`,`permission_key`,`tool_name`,`resource_type`,`resource_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_action_executions` (
  `execution_id` varchar(160) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `attempt` bigint unsigned NOT NULL,
  `executor_type` varchar(32) NOT NULL,
  `executor_ref_json` longtext NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `status` varchar(32) NOT NULL,
  `external_request_id` varchar(128) DEFAULT NULL,
  `result_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`execution_id`),
  UNIQUE KEY `uk_ai_action_executions_attempt` (`workspace_id`,`action_id`,`attempt`),
  UNIQUE KEY `uk_ai_action_executions_idempotency` (`workspace_id`,`action_id`,`idempotency_key`),
  KEY `idx_ai_action_executions_action` (`workspace_id`,`action_id`,`attempt`),
  KEY `idx_ai_action_executions_run` (`workspace_id`,`runtime_run_id`,`attempt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_action_events` (
  `event_id` varchar(128) NOT NULL,
  `event_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` varchar(128) DEFAULT NULL,
  `entry_id` bigint unsigned DEFAULT NULL,
  `event_type` varchar(96) NOT NULL,
  `visibility` varchar(32) NOT NULL DEFAULT 'public',
  `payload_json` longtext NOT NULL,
  `display_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uk_ai_action_events_run_seq` (`workspace_id`,`runtime_run_id`,`event_seq`),
  KEY `idx_ai_action_events_run` (`workspace_id`,`runtime_run_id`,`event_seq`),
  KEY `idx_ai_action_events_action` (`workspace_id`,`action_id`,`event_seq`),
  KEY `idx_ai_action_events_session` (`workspace_id`,`session_id`,`event_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_runtime_event_sequences` (
  `session_id` varchar(191) NOT NULL,
  `last_seq` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_runtime_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `session_id` varchar(191) NOT NULL,
  `runtime_run_id` varchar(191) DEFAULT NULL,
  `event_seq` bigint unsigned NOT NULL,
  `event_id` varchar(191) NOT NULL,
  `event_type` varchar(96) NOT NULL,
  `event_json` json NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_runtime_events_session_seq` (`session_id`,`event_seq`),
  UNIQUE KEY `uk_ai_agent_runtime_events_event_id` (`event_id`),
  KEY `idx_ai_agent_runtime_events_run_seq` (`runtime_run_id`,`event_seq`),
  KEY `idx_ai_agent_runtime_events_session_type` (`session_id`,`event_type`,`event_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_runtime_artifacts` (
  `artifact_id` varchar(128) NOT NULL,
  `artifact_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` varchar(128) DEFAULT NULL,
  `event_id` varchar(128) DEFAULT NULL,
  `visibility` varchar(32) NOT NULL,
  `artifact_type` varchar(64) NOT NULL,
  `mime_type` varchar(128) NOT NULL,
  `size_bytes` bigint unsigned NOT NULL,
  `storage_ref` longtext NOT NULL,
  `preview_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`artifact_id`),
  UNIQUE KEY `uk_ai_runtime_artifacts_artifact_id` (`workspace_id`,`artifact_id`),
  KEY `idx_ai_runtime_artifacts_run` (`workspace_id`,`runtime_run_id`,`artifact_seq`),
  KEY `idx_ai_runtime_artifacts_action` (`workspace_id`,`action_id`,`artifact_seq`),
  KEY `idx_ai_runtime_artifacts_event` (`workspace_id`,`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_child_run_links` (
  `child_run_link_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `parent_action_id` varchar(128) NOT NULL,
  `parent_action_internal_id` bigint unsigned NOT NULL,
  `child_seq` bigint unsigned NOT NULL,
  `child_session_id` bigint unsigned NOT NULL,
  `child_runtime_run_id` varchar(64) NOT NULL,
  `child_profile_id` bigint unsigned NOT NULL,
  `child_profile_version_id` bigint unsigned NOT NULL,
  `snapshot_digest` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`child_run_link_id`),
  UNIQUE KEY `uk_ai_child_run_links_action_child` (`workspace_id`,`parent_action_id`,`child_runtime_run_id`),
  UNIQUE KEY `uk_ai_child_run_links_child_run` (`workspace_id`,`child_runtime_run_id`),
  KEY `idx_ai_child_run_links_parent` (`workspace_id`,`parent_runtime_run_id`,`child_seq`),
  KEY `idx_ai_child_run_links_session` (`workspace_id`,`child_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_agent_resource_versions` (
  `id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `revision` bigint unsigned NOT NULL,
  `source_version` varchar(128) NOT NULL,
  `snapshot_digest` varchar(96) NOT NULL,
  `snapshot_json` longtext NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_resource_versions_revision` (`workspace_id`,`resource_id`,`revision`),
  KEY `idx_ai_agent_resource_versions_digest` (`workspace_id`,`resource_id`,`snapshot_digest`),
  KEY `idx_ai_agent_resource_versions_created` (`workspace_id`,`resource_id`,`created_at`),
  CONSTRAINT `fk_ai_agent_resource_versions_resource`
    FOREIGN KEY (`resource_id`) REFERENCES `ai_agent_resources` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `ai_session_queue_items` (
  `queue_item_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `item_seq` bigint unsigned NOT NULL,
  `position` bigint unsigned NOT NULL,
  `mode` varchar(32) NOT NULL,
  `content` longtext NOT NULL,
  `attachments_json` longtext NOT NULL,
  `context_ref_json` longtext NOT NULL,
  `target_run_id` varchar(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `client_item_id` varchar(64) NOT NULL,
  `claimed_by` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `consumed_runtime_run_id` varchar(64) DEFAULT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`queue_item_id`),
  UNIQUE KEY `uk_ai_session_queue_client_item` (`workspace_id`,`session_id`,`client_item_id`),
  UNIQUE KEY `uk_ai_session_queue_item_seq` (`workspace_id`,`session_id`,`item_seq`),
  KEY `idx_ai_session_queue_pending_order` (`workspace_id`,`session_id`,`status`,`position`,`item_seq`),
  KEY `idx_ai_session_queue_claim` (`status`,`claim_expires_at`),
  CONSTRAINT `fk_ai_session_queue_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- MCP tokens (final baseline)
CREATE TABLE `mcp_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `name` varchar(96) NOT NULL,
  `token_hash` varchar(96) NOT NULL,
  `token_encrypted` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `last_used_at` datetime(3) DEFAULT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mcp_tokens_workspace_user_name` (`workspace_id`,`user_id`,`name`),
  UNIQUE KEY `uk_mcp_tokens_token_hash` (`token_hash`),
  KEY `idx_mcp_tokens_workspace_id` (`workspace_id`),
  KEY `idx_mcp_tokens_user_id` (`user_id`),
  KEY `idx_mcp_tokens_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

