CREATE TABLE `resource_terminal_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `session_id` varchar(64) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `credential_id` bigint unsigned NOT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `endpoint` varchar(512) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `owner_server_id` varchar(128) DEFAULT NULL,
  `owner_connection_id` varchar(64) DEFAULT NULL,
  `attached_by` bigint unsigned DEFAULT NULL,
  `attached_at` bigint DEFAULT NULL,
  `close_reason` varchar(128) DEFAULT NULL,
  `closed_at` bigint DEFAULT NULL,
  `closed_by` bigint unsigned DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_resource_terminal_sessions_session_id` (`session_id`),
  KEY `idx_resource_terminal_sessions_workspace_id` (`workspace_id`),
  KEY `idx_resource_terminal_sessions_resource_id` (`resource_id`),
  KEY `idx_resource_terminal_sessions_credential_id` (`credential_id`),
  KEY `idx_resource_terminal_sessions_agent_id` (`agent_id`),
  KEY `idx_resource_terminal_sessions_resource_type` (`resource_type`),
  KEY `idx_resource_terminal_sessions_status` (`status`),
  KEY `idx_resource_terminal_sessions_owner_server_id` (`owner_server_id`),
  KEY `idx_resource_terminal_sessions_owner_connection_id` (`owner_connection_id`),
  KEY `idx_resource_terminal_sessions_attached_by` (`attached_by`),
  KEY `idx_resource_terminal_sessions_closed_by` (`closed_by`),
  KEY `idx_resource_terminal_sessions_created_by` (`created_by`),
  CONSTRAINT `fk_resource_terminal_sessions_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_resource` FOREIGN KEY (`resource_id`) REFERENCES `resources` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_attacher` FOREIGN KEY (`attached_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_closer` FOREIGN KEY (`closed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_resource_terminal_sessions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
