CREATE TABLE `notification_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext,
  `priority` bigint DEFAULT '0',
  `metadata` longtext,
  `idempotency_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_events_idempotency_key` (`idempotency_key`),
  KEY `idx_notification_events_workspace_id` (`workspace_id`),
  KEY `idx_notification_events_family` (`family`),
  KEY `idx_notification_events_resource_type` (`resource_type`),
  KEY `idx_notification_events_resource_id` (`resource_id`),
  KEY `idx_notification_events_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notification_events_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notification_events_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_audiences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `permission_policy` varchar(64) DEFAULT 'workspace_member',
  `audience_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_audiences_audience_key` (`audience_key`),
  KEY `idx_notification_audiences_event_id` (`event_id`),
  KEY `idx_notification_audiences_workspace_id` (`workspace_id`),
  KEY `idx_notification_audiences_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notification_audiences_resource_type` (`resource_type`),
  KEY `idx_notification_audiences_resource_id` (`resource_id`),
  CONSTRAINT `fk_notification_audiences_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notification_audiences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notification_audiences_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notifications` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `event_id` bigint unsigned NOT NULL,
  `audience_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `recipient_user_id` bigint unsigned DEFAULT NULL,
  `recipient_email` varchar(255) DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `event_type` varchar(64) NOT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `actor_type` varchar(32) DEFAULT 'system',
  `title` varchar(256) NOT NULL,
  `content` longtext,
  `priority` bigint DEFAULT '0',
  `metadata` longtext,
  `canonical_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notifications_canonical_key` (`canonical_key`),
  KEY `idx_notifications_event_id` (`event_id`),
  KEY `idx_notifications_audience_id` (`audience_id`),
  KEY `idx_notifications_workspace_id` (`workspace_id`),
  KEY `idx_notifications_recipient_user_id` (`recipient_user_id`),
  KEY `idx_notifications_family` (`family`),
  KEY `idx_notifications_resource_type` (`resource_type`),
  KEY `idx_notifications_resource_id` (`resource_id`),
  KEY `idx_notifications_actor_user_id` (`actor_user_id`),
  CONSTRAINT `fk_notifications_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  CONSTRAINT `fk_notifications_audience` FOREIGN KEY (`audience_id`) REFERENCES `notification_audiences` (`id`),
  CONSTRAINT `fk_notifications_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_notifications_recipient_user` FOREIGN KEY (`recipient_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notifications_actor_user` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_deliveries` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `notification_id` bigint unsigned NOT NULL,
  `channel` varchar(32) NOT NULL,
  `destination` varchar(255) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `provider` varchar(64) DEFAULT NULL,
  `external_ref` varchar(191) DEFAULT NULL,
  `error_message` text,
  `sent_at` bigint DEFAULT NULL,
  `read_at` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_delivery_channel` (`notification_id`,`channel`),
  KEY `idx_notification_deliveries_status` (`status`),
  CONSTRAINT `fk_notification_deliveries_notification` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `notification_preferences` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `user_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned DEFAULT NULL,
  `resource_type` varchar(64) DEFAULT NULL,
  `resource_id` bigint unsigned DEFAULT NULL,
  `family` varchar(64) NOT NULL,
  `channel` varchar(32) NOT NULL,
  `enabled` tinyint(1) NOT NULL DEFAULT '1',
  `rule_key` varchar(191) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_notification_preferences_rule_key` (`rule_key`),
  KEY `idx_notification_preferences_user_id` (`user_id`),
  KEY `idx_notification_preferences_workspace_id` (`workspace_id`),
  KEY `idx_notification_preferences_resource_type` (`resource_type`),
  KEY `idx_notification_preferences_resource_id` (`resource_id`),
  KEY `idx_notification_preferences_family` (`family`),
  KEY `idx_notification_preferences_channel` (`channel`),
  CONSTRAINT `fk_notification_preferences_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_notification_preferences_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE `messages`
  ADD COLUMN `notification_id` bigint unsigned DEFAULT NULL AFTER `updated_at`,
  ADD COLUMN `event_id` bigint unsigned DEFAULT NULL AFTER `notification_id`,
  ADD COLUMN `audience_id` bigint unsigned DEFAULT NULL AFTER `event_id`,
  ADD COLUMN `event_type` varchar(64) DEFAULT NULL AFTER `type`,
  ADD COLUMN `channel` varchar(32) DEFAULT 'in_app' AFTER `metadata`,
  ADD COLUMN `resource_type` varchar(64) DEFAULT NULL AFTER `channel`,
  ADD COLUMN `resource_id` bigint unsigned DEFAULT NULL AFTER `resource_type`,
  ADD UNIQUE KEY `idx_messages_notification_id` (`notification_id`),
  ADD KEY `idx_messages_event_id` (`event_id`),
  ADD KEY `idx_messages_audience_id` (`audience_id`),
  ADD KEY `idx_messages_resource_type` (`resource_type`),
  ADD KEY `idx_messages_resource_id` (`resource_id`),
  ADD CONSTRAINT `fk_messages_notification` FOREIGN KEY (`notification_id`) REFERENCES `notifications` (`id`),
  ADD CONSTRAINT `fk_messages_event` FOREIGN KEY (`event_id`) REFERENCES `notification_events` (`id`),
  ADD CONSTRAINT `fk_messages_audience` FOREIGN KEY (`audience_id`) REFERENCES `notification_audiences` (`id`);
