RENAME TABLE `llm_model_catalogs` TO `ai_model_catalogs`;

ALTER TABLE `ai_model_catalogs`
  RENAME INDEX `idx_llm_model_catalogs_name` TO `idx_ai_model_catalogs_name`,
  RENAME INDEX `idx_llm_model_catalog_source_ref` TO `idx_ai_model_catalog_source_ref`,
  RENAME INDEX `idx_llm_model_catalogs_imported_by` TO `idx_ai_model_catalogs_imported_by`,
  DROP FOREIGN KEY `fk_llm_model_catalogs_importer`,
  ADD CONSTRAINT `fk_ai_model_catalogs_importer` FOREIGN KEY (`imported_by`) REFERENCES `users` (`id`);

ALTER TABLE `deployment_requests`
  CHANGE COLUMN `llm_model_id` `ai_model_id` bigint unsigned DEFAULT NULL,
  CHANGE COLUMN `llm_model_snapshot` `ai_model_snapshot` longtext,
  RENAME INDEX `idx_deployment_requests_llm_model_id` TO `idx_deployment_requests_ai_model_id`,
  DROP FOREIGN KEY `fk_deployment_requests_llm_model`,
  ADD CONSTRAINT `fk_deployment_requests_ai_model` FOREIGN KEY (`ai_model_id`) REFERENCES `ai_model_catalogs` (`id`);

UPDATE `store_templates` SET `template_type` = 'ai' WHERE `template_type` = 'llm';
UPDATE `deployment_requests` SET `template_type` = 'ai' WHERE `template_type` = 'llm';

CREATE TABLE `ai_providers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `provider_type` varchar(64) NOT NULL,
  `base_url` varchar(512) DEFAULT NULL,
  `credential_id` bigint unsigned DEFAULT NULL,
  `headers_json` longtext,
  `settings_json` longtext,
  `metadata_json` longtext,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_providers_workspace_id` (`workspace_id`),
  KEY `idx_ai_providers_name` (`name`),
  KEY `idx_ai_providers_provider_type` (`provider_type`),
  KEY `idx_ai_providers_status` (`status`),
  KEY `idx_ai_providers_credential_id` (`credential_id`),
  KEY `idx_ai_providers_created_by` (`created_by`),
  CONSTRAINT `fk_ai_providers_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_ai_providers_credential` FOREIGN KEY (`credential_id`) REFERENCES `credentials` (`id`),
  CONSTRAINT `fk_ai_providers_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ai_model_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `model_id` bigint unsigned NOT NULL,
  `provider_id` bigint unsigned NOT NULL,
  `provider_model_key` varchar(255) DEFAULT NULL,
  `capabilities_json` longtext,
  `settings_json` longtext,
  `metadata_json` longtext,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_model_bindings_workspace_id` (`workspace_id`),
  KEY `idx_ai_model_bindings_model_id` (`model_id`),
  KEY `idx_ai_model_bindings_provider_id` (`provider_id`),
  KEY `idx_ai_model_bindings_status` (`status`),
  KEY `idx_ai_model_bindings_created_by` (`created_by`),
  CONSTRAINT `fk_ai_model_bindings_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_ai_model_bindings_model` FOREIGN KEY (`model_id`) REFERENCES `ai_model_catalogs` (`id`),
  CONSTRAINT `fk_ai_model_bindings_provider` FOREIGN KEY (`provider_id`) REFERENCES `ai_providers` (`id`),
  CONSTRAINT `fk_ai_model_bindings_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ai_agents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text,
  `scenario` varchar(64) NOT NULL,
  `scope_type` varchar(32) DEFAULT 'workspace',
  `system_prompt` longtext,
  `user_prompt_template` longtext,
  `input_schema_json` longtext,
  `output_schema_json` longtext,
  `tool_policy_json` longtext,
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_agents_workspace_id` (`workspace_id`),
  KEY `idx_ai_agents_name` (`name`),
  KEY `idx_ai_agents_scenario` (`scenario`),
  KEY `idx_ai_agents_scope_type` (`scope_type`),
  KEY `idx_ai_agents_status` (`status`),
  KEY `idx_ai_agents_created_by` (`created_by`),
  CONSTRAINT `fk_ai_agents_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_ai_agents_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ai_runtime_profiles` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `agent_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `model_id` bigint unsigned NOT NULL,
  `binding_priority_json` longtext,
  `runtime_settings_json` longtext,
  `fallback_enabled` tinyint(1) DEFAULT '1',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_runtime_profiles_workspace_id` (`workspace_id`),
  KEY `idx_ai_runtime_profiles_agent_id` (`agent_id`),
  KEY `idx_ai_runtime_profiles_model_id` (`model_id`),
  KEY `idx_ai_runtime_profiles_status` (`status`),
  KEY `idx_ai_runtime_profiles_created_by` (`created_by`),
  CONSTRAINT `fk_ai_runtime_profiles_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_ai_runtime_profiles_agent` FOREIGN KEY (`agent_id`) REFERENCES `ai_agents` (`id`),
  CONSTRAINT `fk_ai_runtime_profiles_model` FOREIGN KEY (`model_id`) REFERENCES `ai_model_catalogs` (`id`),
  CONSTRAINT `fk_ai_runtime_profiles_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ai_sessions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `pipeline_run_id` bigint unsigned DEFAULT NULL,
  `task_id` bigint unsigned DEFAULT NULL,
  `node_id` varchar(128) DEFAULT NULL,
  `scenario` varchar(64) NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'queued',
  `runtime_profile_id` bigint unsigned DEFAULT NULL,
  `provider_id` bigint unsigned DEFAULT NULL,
  `model_id` bigint unsigned DEFAULT NULL,
  `binding_id` bigint unsigned DEFAULT NULL,
  `agent_id` bigint unsigned DEFAULT NULL,
  `request_json` longtext,
  `response_json` longtext,
  `error_msg` text,
  `started_at` bigint DEFAULT NULL,
  `completed_at` bigint DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_sessions_workspace_id` (`workspace_id`),
  KEY `idx_ai_sessions_pipeline_run_id` (`pipeline_run_id`),
  KEY `idx_ai_sessions_task_id` (`task_id`),
  KEY `idx_ai_sessions_node_id` (`node_id`),
  KEY `idx_ai_sessions_scenario` (`scenario`),
  KEY `idx_ai_sessions_status` (`status`),
  KEY `idx_ai_sessions_runtime_profile_id` (`runtime_profile_id`),
  KEY `idx_ai_sessions_provider_id` (`provider_id`),
  KEY `idx_ai_sessions_model_id` (`model_id`),
  KEY `idx_ai_sessions_binding_id` (`binding_id`),
  KEY `idx_ai_sessions_agent_id` (`agent_id`),
  KEY `idx_ai_sessions_started_at` (`started_at`),
  KEY `idx_ai_sessions_completed_at` (`completed_at`),
  KEY `idx_ai_sessions_created_by` (`created_by`),
  CONSTRAINT `fk_ai_sessions_workspace` FOREIGN KEY (`workspace_id`) REFERENCES `workspaces` (`id`),
  CONSTRAINT `fk_ai_sessions_pipeline_run` FOREIGN KEY (`pipeline_run_id`) REFERENCES `pipeline_runs` (`id`),
  CONSTRAINT `fk_ai_sessions_task` FOREIGN KEY (`task_id`) REFERENCES `agent_tasks` (`id`),
  CONSTRAINT `fk_ai_sessions_runtime_profile` FOREIGN KEY (`runtime_profile_id`) REFERENCES `ai_runtime_profiles` (`id`),
  CONSTRAINT `fk_ai_sessions_provider` FOREIGN KEY (`provider_id`) REFERENCES `ai_providers` (`id`),
  CONSTRAINT `fk_ai_sessions_model` FOREIGN KEY (`model_id`) REFERENCES `ai_model_catalogs` (`id`),
  CONSTRAINT `fk_ai_sessions_binding` FOREIGN KEY (`binding_id`) REFERENCES `ai_model_bindings` (`id`),
  CONSTRAINT `fk_ai_sessions_agent` FOREIGN KEY (`agent_id`) REFERENCES `ai_agents` (`id`),
  CONSTRAINT `fk_ai_sessions_creator` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
