CREATE TABLE `resource_operation_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `resource_type` varchar(32) NOT NULL,
  `domain` varchar(32) NOT NULL,
  `namespace` varchar(128) DEFAULT NULL,
  `target_kind` varchar(64) DEFAULT NULL,
  `target_name` varchar(255) DEFAULT NULL,
  `action` varchar(64) NOT NULL,
  `reason` text,
  `request_snapshot` longtext,
  `result_summary` text,
  `error_message` text,
  `task_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'queued',
  `created_by` bigint unsigned NOT NULL,
  `completed_at` bigint DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_resource_operation_audits_workspace_id` (`workspace_id`),
  KEY `idx_resource_operation_audits_resource_id` (`resource_id`),
  KEY `idx_resource_operation_audits_resource_type` (`resource_type`),
  KEY `idx_resource_operation_audits_domain` (`domain`),
  KEY `idx_resource_operation_audits_namespace` (`namespace`),
  KEY `idx_resource_operation_audits_target_kind` (`target_kind`),
  KEY `idx_resource_operation_audits_target_name` (`target_name`),
  KEY `idx_resource_operation_audits_action` (`action`),
  KEY `idx_resource_operation_audits_task_id` (`task_id`),
  KEY `idx_resource_operation_audits_status` (`status`),
  KEY `idx_resource_operation_audits_created_by` (`created_by`),
  KEY `idx_resource_operation_audits_completed_at` (`completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
