CREATE TABLE IF NOT EXISTS `ai_runtime_sequences` (
  `name` varchar(96) NOT NULL,
  `next_value` bigint unsigned NOT NULL DEFAULT 1,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_profiles` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `profile_kind` varchar(64) NOT NULL DEFAULT 'generic',
  `context_tags_json` longtext NOT NULL,
  `provider_json` longtext NOT NULL,
  `binding_json` longtext NOT NULL,
  `model_json` longtext NOT NULL,
  `provider_credential_ref_json` longtext NOT NULL,
  `inference_json` longtext NOT NULL,
  `prompt_json` longtext NOT NULL,
  `context_contract_json` longtext NOT NULL,
  `input_schema_json` longtext NOT NULL,
  `output_schema_json` longtext NOT NULL,
  `memory_policy_json` longtext NOT NULL,
  `confirmation_policy_json` longtext NOT NULL,
  `response_mode` varchar(32) NOT NULL DEFAULT 'text',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_profiles_workspace_name` (`workspace_id`,`name`),
  KEY `idx_ai_agent_profiles_workspace_status` (`workspace_id`,`status`),
  KEY `idx_ai_agent_profiles_workspace_kind` (`workspace_id`,`profile_kind`),
  KEY `idx_ai_agent_profiles_workspace_updated` (`workspace_id`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_profile_resource_refs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `profile_section` varchar(48) NOT NULL,
  `resource_type` varchar(64) NOT NULL,
  `resource_id` varchar(128) NOT NULL,
  `resource_id_kind` enum('database_id','resource_key') NOT NULL,
  `resource_version_id` bigint unsigned DEFAULT NULL,
  `resource_version` varchar(128) DEFAULT NULL,
  `snapshot_digest` varchar(96) DEFAULT NULL,
  `config_json` longtext NOT NULL,
  `required` tinyint NOT NULL DEFAULT 1,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_profile_resource_refs_profile` (`workspace_id`,`profile_id`,`profile_section`),
  KEY `idx_ai_profile_resource_refs_resource` (`workspace_id`,`resource_type`,`resource_id`),
  KEY `idx_ai_profile_resource_refs_version` (`workspace_id`,`resource_version_id`),
  CONSTRAINT `fk_ai_profile_resource_refs_profile` FOREIGN KEY (`profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_resources` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `resource_kind` varchar(48) NOT NULL,
  `resource_key` varchar(128) NOT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `version` varchar(128) NOT NULL DEFAULT 'latest',
  `status` varchar(32) NOT NULL DEFAULT 'draft',
  `spec_json` longtext NOT NULL,
  `endpoint_json` longtext NOT NULL,
  `secret_ref_json` longtext NOT NULL,
  `tags_json` longtext NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_resources_key` (`workspace_id`,`resource_kind`,`resource_key`),
  KEY `idx_ai_agent_resources_kind_status` (`workspace_id`,`resource_kind`,`status`),
  KEY `idx_ai_agent_resources_updated` (`workspace_id`,`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_resource_versions` (
  `id` bigint unsigned NOT NULL,
  `resource_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `revision` bigint unsigned NOT NULL,
  `source_version` varchar(128) NOT NULL,
  `snapshot_digest` varchar(96) NOT NULL,
  `snapshot_json` longtext NOT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_resource_versions_revision` (`workspace_id`,`resource_id`,`revision`),
  KEY `idx_ai_agent_resource_versions_digest` (`workspace_id`,`resource_id`,`snapshot_digest`),
  KEY `idx_ai_agent_resource_versions_created` (`workspace_id`,`resource_id`,`created_at`),
  CONSTRAINT `fk_ai_agent_resource_versions_resource`
    FOREIGN KEY (`resource_id`) REFERENCES `ai_agent_resources` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_profile_versions` (
  `id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `version` int unsigned NOT NULL,
  `snapshot_hash` varchar(96) NOT NULL,
  `snapshot_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'published',
  `published_by` bigint unsigned NOT NULL,
  `published_at` datetime(3) NOT NULL,
  `change_summary` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_profile_versions_profile_version` (`profile_id`,`version`),
  UNIQUE KEY `uk_ai_profile_versions_hash` (`workspace_id`,`snapshot_hash`),
  KEY `idx_ai_profile_versions_workspace_profile` (`workspace_id`,`profile_id`),
  CONSTRAINT `fk_ai_profile_versions_profile` FOREIGN KEY (`profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_profile_validation_results` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workspace_id` bigint unsigned NOT NULL,
  `profile_id` bigint unsigned NOT NULL,
  `profile_version_id` bigint unsigned DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `result_json` longtext NOT NULL,
  `validated_by` bigint unsigned NOT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_profile_validation_profile` (`workspace_id`,`profile_id`,`created_at`),
  KEY `idx_ai_profile_validation_version` (`workspace_id`,`profile_version_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `workspace_ai_settings` (
  `workspace_id` bigint unsigned NOT NULL,
  `settings_json` longtext NOT NULL,
  `updated_by` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`workspace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_runtime_workspaces` (
  `id` bigint unsigned NOT NULL,
  `workspace_runtime_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_user_id` bigint unsigned NOT NULL,
  `workspace_key` varchar(128) NOT NULL,
  `provider` varchar(32) NOT NULL,
  `provider_endpoint` varchar(512) DEFAULT NULL,
  `sandbox_id` varchar(191) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `image` varchar(512) NOT NULL,
  `root_path` varchar(512) NOT NULL,
  `repository_json` longtext NOT NULL,
  `network_policy_json` longtext NOT NULL,
  `secret_refs_json` longtext NOT NULL,
  `quota_json` longtext NOT NULL,
  `snapshot_hash` varchar(96) NOT NULL,
  `lease_owner_instance_id` varchar(191) DEFAULT NULL,
  `lease_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `lease_expires_at` datetime(3) DEFAULT NULL,
  `provision_owner_instance_id` varchar(128) DEFAULT NULL,
  `provision_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `provision_expires_at` datetime(3) DEFAULT NULL,
  `state_version` bigint unsigned NOT NULL DEFAULT 0,
  `last_connected_at` datetime(3) DEFAULT NULL,
  `paused_at` datetime(3) DEFAULT NULL,
  `recycled_at` datetime(3) DEFAULT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_workspaces_runtime_id` (`workspace_runtime_id`),
  UNIQUE KEY `uk_ai_runtime_workspaces_owner_key` (`workspace_id`,`owner_user_id`,`workspace_key`),
  KEY `idx_ai_runtime_workspaces_owner_status` (`workspace_id`,`owner_user_id`,`status`,`updated_at`),
  KEY `idx_ai_runtime_workspaces_lease` (`status`,`lease_expires_at`),
  KEY `idx_ai_runtime_workspaces_provision` (`status`,`provision_expires_at`,`provision_owner_instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_runtime_workspace_audits` (
  `audit_id` varchar(160) NOT NULL,
  `workspace_runtime_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `owner_user_id` bigint unsigned NOT NULL,
  `actor_user_id` bigint unsigned NOT NULL,
  `operation` varchar(32) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `details_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`audit_id`),
  KEY `idx_ai_runtime_workspace_audits_workspace` (`workspace_id`,`workspace_runtime_id`,`created_at`),
  KEY `idx_ai_runtime_workspace_audits_actor` (`workspace_id`,`actor_user_id`,`created_at`),
  CONSTRAINT `fk_ai_runtime_workspace_audits_workspace` FOREIGN KEY (`workspace_runtime_id`) REFERENCES `ai_runtime_workspaces` (`workspace_runtime_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_sessions` (
  `id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `session_kind` varchar(32) NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `auth_session_id` varchar(128) NOT NULL,
  `business_type` varchar(64) DEFAULT NULL,
  `business_id` varchar(160) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'active',
  `agent_profile_id` bigint unsigned NOT NULL,
  `agent_profile_version_id` bigint unsigned NOT NULL,
  `agent_profile_version_key` varchar(64) NOT NULL DEFAULT '',
  `agent_profile_snapshot_hash` varchar(96) NOT NULL,
  `agent_workspace_runtime_id` varchar(128) NOT NULL,
  `agent_workspace_snapshot_hash` varchar(96) NOT NULL,
  `session_key` varchar(512) DEFAULT NULL,
  `first_session_timestamp` datetime(3) DEFAULT NULL,
  `source` varchar(64) DEFAULT NULL,
  `model_override_json` longtext NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `entry_count` bigint unsigned NOT NULL DEFAULT 0,
  `last_entry_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_sessions_current` (`workspace_id`,`user_id`,`auth_session_id`,`session_kind`),
  KEY `idx_ai_sessions_business` (`workspace_id`,`business_type`,`business_id`),
  KEY `idx_ai_sessions_profile` (`workspace_id`,`agent_profile_id`,`agent_profile_version_id`),
  KEY `idx_ai_sessions_profile_key` (`workspace_id`,`agent_profile_id`,`agent_profile_version_key`,`status`,`updated_at`),
  KEY `idx_ai_sessions_session_key` (`workspace_id`,`session_key`),
  KEY `idx_ai_sessions_updated` (`workspace_id`,`updated_at`),
  CONSTRAINT `fk_ai_sessions_agent_profile`
    FOREIGN KEY (`agent_profile_id`) REFERENCES `ai_agent_profiles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_session_entries` (
  `id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `user_id` bigint unsigned NOT NULL,
  `parent_entry_id` bigint unsigned DEFAULT NULL,
  `seq` bigint unsigned NOT NULL,
  `entry_type` varchar(32) NOT NULL,
  `role` varchar(32) NOT NULL,
  `status` varchar(32) NOT NULL,
  `content` longtext DEFAULT NULL,
  `content_blocks_json` longtext NOT NULL,
  `input_json` longtext NOT NULL,
  `output_json` longtext NOT NULL,
  `runtime_run_id` varchar(64) DEFAULT NULL,
  `event_seq` bigint unsigned DEFAULT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_entries_seq` (`session_id`,`seq`),
  UNIQUE KEY `uk_ai_session_entries_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_session_entries_session` (`workspace_id`,`session_id`,`created_at`),
  KEY `idx_ai_session_entries_run` (`workspace_id`,`runtime_run_id`),
  CONSTRAINT `fk_ai_session_entries_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_current_sessions` (
  `session_key` varchar(512) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`session_key`),
  KEY `idx_ai_current_sessions_workspace` (`workspace_id`,`updated_at`),
  CONSTRAINT `fk_ai_current_sessions_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_session_queue_items` (
  `queue_item_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `item_seq` bigint unsigned NOT NULL,
  `position` bigint unsigned NOT NULL,
  `mode` varchar(32) NOT NULL,
  `content` longtext NOT NULL,
  `attachments_json` longtext NOT NULL,
  `context_ref_json` longtext NOT NULL,
  `target_run_id` varchar(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `client_item_id` varchar(64) NOT NULL,
  `claimed_by` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `consumed_runtime_run_id` varchar(64) DEFAULT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`queue_item_id`),
  UNIQUE KEY `uk_ai_session_queue_client_item` (`workspace_id`,`session_id`,`client_item_id`),
  UNIQUE KEY `uk_ai_session_queue_item_seq` (`workspace_id`,`session_id`,`item_seq`),
  KEY `idx_ai_session_queue_pending_order` (`workspace_id`,`session_id`,`status`,`position`,`item_seq`),
  KEY `idx_ai_session_queue_claim` (`status`,`claim_expires_at`),
  CONSTRAINT `fk_ai_session_queue_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_runtime_runs` (
  `id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `agent_profile_id` bigint unsigned NOT NULL,
  `agent_profile_version_id` bigint unsigned NOT NULL,
  `agent_profile_version_key` varchar(64) NOT NULL DEFAULT '',
  `agent_profile_snapshot_hash` varchar(96) NOT NULL,
  `agent_workspace_runtime_id` varchar(128) NOT NULL,
  `agent_workspace_snapshot_hash` varchar(96) NOT NULL,
  `profile_snapshot_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL,
  `active_slot` varchar(16) DEFAULT NULL,
  `owner_instance_id` varchar(191) DEFAULT NULL,
  `owner_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `owner_lease_expires_at` datetime(3) DEFAULT NULL,
  `input_entry_id` bigint unsigned NOT NULL,
  `output_entry_id` bigint unsigned DEFAULT NULL,
  `request_json` longtext NOT NULL,
  `result_json` longtext NOT NULL,
  `usage_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_runtime_runs_run` (`runtime_run_id`),
  UNIQUE KEY `uk_ai_runtime_runs_active_root` (`workspace_id`,`session_id`,`active_slot`),
  KEY `idx_ai_runtime_runs_session` (`workspace_id`,`session_id`,`created_at`),
  KEY `idx_ai_runtime_runs_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_ai_runtime_runs_owner_lease` (`status`,`owner_lease_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_actions` (
  `id` bigint unsigned NOT NULL,
  `action_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `context_tags_json` longtext NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `entry_id` bigint unsigned DEFAULT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_kind` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `source` varchar(32) NOT NULL,
  `capability_id` varchar(96) NOT NULL,
  `input_json` longtext NOT NULL,
  `input_digest` varchar(71) NOT NULL,
  `target_json` longtext NOT NULL,
  `policy_json` longtext NOT NULL,
  `display_json` longtext NOT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'awaiting_decision',
  `requested_by` bigint unsigned NOT NULL,
  `decided_by` bigint unsigned DEFAULT NULL,
  `decided_at` datetime(3) DEFAULT NULL,
  `executed_at` datetime(3) DEFAULT NULL,
  `result_json` longtext NOT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_actions_action_id` (`workspace_id`,`action_id`),
  UNIQUE KEY `uk_ai_agent_actions_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_agent_actions_status` (`workspace_id`,`status`,`created_at`),
  KEY `idx_ai_agent_actions_session` (`workspace_id`,`session_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_action_decisions` (
  `decision_id` varchar(160) NOT NULL,
  `decision_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `decision_type` varchar(32) NOT NULL,
  `decision` varchar(32) NOT NULL,
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `reason` text DEFAULT NULL,
  `input_patch_json` longtext NOT NULL,
  `client_decision_id` varchar(64) NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`decision_id`),
  UNIQUE KEY `uk_ai_action_decisions_client` (`workspace_id`,`action_id`,`actor_user_id`,`client_decision_id`),
  UNIQUE KEY `uk_ai_action_decisions_idempotency` (`workspace_id`,`idempotency_key`),
  KEY `idx_ai_action_decisions_action` (`workspace_id`,`action_id`,`decision_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_session_permission_grants` (
  `grant_id` varchar(160) NOT NULL,
  `grant_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `permission_key` varchar(160) NOT NULL,
  `tool_name` varchar(128) NOT NULL,
  `executor_type` varchar(32) NOT NULL,
  `resource_type` varchar(96) NOT NULL,
  `resource_id` varchar(160) NOT NULL,
  `status` varchar(32) NOT NULL,
  `granted_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `expires_at` datetime(3) NOT NULL,
  `revoked_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`grant_id`),
  UNIQUE KEY `uk_ai_session_permission_grants_id` (`workspace_id`,`grant_id`),
  KEY `idx_ai_session_permission_grants_session` (`workspace_id`,`session_id`,`status`,`expires_at`),
  KEY `idx_ai_session_permission_grants_match` (`workspace_id`,`session_id`,`permission_key`,`tool_name`,`resource_type`,`resource_id`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_action_executions` (
  `execution_id` varchar(160) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` bigint unsigned NOT NULL,
  `attempt` bigint unsigned NOT NULL,
  `executor_type` varchar(32) NOT NULL,
  `executor_ref_json` longtext NOT NULL,
  `idempotency_key` varchar(191) NOT NULL,
  `status` varchar(32) NOT NULL,
  `external_request_id` varchar(128) DEFAULT NULL,
  `result_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `finished_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`execution_id`),
  UNIQUE KEY `uk_ai_action_executions_attempt` (`workspace_id`,`action_id`,`attempt`),
  UNIQUE KEY `uk_ai_action_executions_idempotency` (`workspace_id`,`action_id`,`idempotency_key`),
  KEY `idx_ai_action_executions_action` (`workspace_id`,`action_id`,`attempt`),
  KEY `idx_ai_action_executions_run` (`workspace_id`,`runtime_run_id`,`attempt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_action_events` (
  `event_id` varchar(128) NOT NULL,
  `event_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` varchar(128) DEFAULT NULL,
  `entry_id` bigint unsigned DEFAULT NULL,
  `event_type` varchar(96) NOT NULL,
  `visibility` varchar(32) NOT NULL DEFAULT 'public',
  `payload_json` longtext NOT NULL,
  `display_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE KEY `uk_ai_action_events_run_seq` (`workspace_id`,`runtime_run_id`,`event_seq`),
  KEY `idx_ai_action_events_run` (`workspace_id`,`runtime_run_id`,`event_seq`),
  KEY `idx_ai_action_events_action` (`workspace_id`,`action_id`,`event_seq`),
  KEY `idx_ai_action_events_session` (`workspace_id`,`session_id`,`event_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_runtime_event_sequences` (
  `session_id` varchar(191) NOT NULL,
  `last_seq` bigint unsigned NOT NULL,
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_agent_runtime_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `session_id` varchar(191) NOT NULL,
  `runtime_run_id` varchar(191) DEFAULT NULL,
  `event_seq` bigint unsigned NOT NULL,
  `event_id` varchar(191) NOT NULL,
  `event_type` varchar(96) NOT NULL,
  `event_json` json NOT NULL,
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_runtime_events_session_seq` (`session_id`,`event_seq`),
  UNIQUE KEY `uk_ai_agent_runtime_events_event_id` (`event_id`),
  KEY `idx_ai_agent_runtime_events_run_seq` (`runtime_run_id`,`event_seq`),
  KEY `idx_ai_agent_runtime_events_session_type` (`session_id`,`event_type`,`event_seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_runtime_artifacts` (
  `artifact_id` varchar(128) NOT NULL,
  `artifact_seq` bigint unsigned NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `runtime_run_id` varchar(64) NOT NULL,
  `action_id` varchar(128) DEFAULT NULL,
  `event_id` varchar(128) DEFAULT NULL,
  `visibility` varchar(32) NOT NULL,
  `artifact_type` varchar(64) NOT NULL,
  `mime_type` varchar(128) NOT NULL,
  `size_bytes` bigint unsigned NOT NULL,
  `storage_ref` longtext NOT NULL,
  `preview_json` longtext NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`artifact_id`),
  UNIQUE KEY `uk_ai_runtime_artifacts_artifact_id` (`workspace_id`,`artifact_id`),
  KEY `idx_ai_runtime_artifacts_run` (`workspace_id`,`runtime_run_id`,`artifact_seq`),
  KEY `idx_ai_runtime_artifacts_action` (`workspace_id`,`action_id`,`artifact_seq`),
  KEY `idx_ai_runtime_artifacts_event` (`workspace_id`,`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_child_run_links` (
  `child_run_link_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `parent_action_id` varchar(128) NOT NULL,
  `parent_action_internal_id` bigint unsigned NOT NULL,
  `child_seq` bigint unsigned NOT NULL,
  `child_session_id` bigint unsigned NOT NULL,
  `child_runtime_run_id` varchar(64) NOT NULL,
  `child_profile_id` bigint unsigned NOT NULL,
  `child_profile_version_id` bigint unsigned NOT NULL,
  `snapshot_digest` varchar(128) NOT NULL,
  `status` varchar(32) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`child_run_link_id`),
  UNIQUE KEY `uk_ai_child_run_links_action_child` (`workspace_id`,`parent_action_id`,`child_runtime_run_id`),
  UNIQUE KEY `uk_ai_child_run_links_child_run` (`workspace_id`,`child_runtime_run_id`),
  KEY `idx_ai_child_run_links_parent` (`workspace_id`,`parent_runtime_run_id`,`child_seq`),
  KEY `idx_ai_child_run_links_session` (`workspace_id`,`child_session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_orchestration_plans` (
  `orchestration_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `parent_session_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL,
  `phase` varchar(48) NOT NULL,
  `context_pack_digest` varchar(96) NOT NULL DEFAULT '',
  `synthesis_summary` longtext NOT NULL,
  `final_summary` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `claim_owner` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`orchestration_id`),
  UNIQUE KEY `uk_ai_orchestration_parent_run` (`workspace_id`,`parent_runtime_run_id`),
  KEY `idx_ai_orchestration_phase` (`workspace_id`,`status`,`phase`),
  KEY `idx_ai_orchestration_claim` (`status`,`claim_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_orchestration_context_packs` (
  `context_pack_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `orchestration_id` varchar(128) NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `source` varchar(64) NOT NULL,
  `trim_rules_json` longtext NOT NULL,
  `resource_versions_json` longtext NOT NULL,
  `token_estimate` bigint unsigned NOT NULL DEFAULT 0,
  `content_json` longtext NOT NULL,
  `digest` varchar(96) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`context_pack_id`),
  UNIQUE KEY `uk_ai_orchestration_context_digest` (`workspace_id`,`orchestration_id`,`digest`),
  KEY `idx_ai_orchestration_context_parent` (`workspace_id`,`parent_runtime_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_orchestration_tasks` (
  `task_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `orchestration_id` varchar(128) NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `task_seq` bigint unsigned NOT NULL,
  `task_kind` varchar(32) NOT NULL DEFAULT 'worker',
  `objective` longtext NOT NULL,
  `assigned_profile_id` bigint unsigned NOT NULL DEFAULT 0,
  `assigned_profile_version_id` bigint unsigned NOT NULL DEFAULT 0,
  `assigned_subagent_name` varchar(191) NOT NULL DEFAULT '',
  `mode` varchar(32) NOT NULL DEFAULT 'read_only',
  `dependency_ids_json` longtext NOT NULL,
  `context_pack_digest` varchar(96) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL,
  `claim_owner` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `attempt` bigint unsigned NOT NULL DEFAULT 0,
  `child_run_link_id` varchar(128) DEFAULT NULL,
  `child_runtime_run_id` varchar(64) DEFAULT NULL,
  `result_summary` longtext NOT NULL,
  `artifact_refs_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE KEY `uk_ai_orchestration_task_seq` (`workspace_id`,`orchestration_id`,`task_seq`),
  KEY `idx_ai_orchestration_task_status` (`workspace_id`,`orchestration_id`,`status`),
  KEY `idx_ai_orchestration_task_claim` (`status`,`claim_expires_at`),
  KEY `idx_ai_orchestration_task_parent` (`workspace_id`,`parent_runtime_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
