CREATE TABLE IF NOT EXISTS `ai_session_queue_items` (
  `queue_item_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `session_id` bigint unsigned NOT NULL,
  `item_seq` bigint unsigned NOT NULL,
  `position` bigint unsigned NOT NULL,
  `mode` varchar(32) NOT NULL,
  `content` longtext NOT NULL,
  `attachments_json` longtext NOT NULL,
  `context_ref_json` longtext NOT NULL,
  `target_run_id` varchar(64) DEFAULT NULL,
  `status` varchar(32) NOT NULL DEFAULT 'pending',
  `client_item_id` varchar(64) NOT NULL,
  `claimed_by` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `expires_at` datetime(3) DEFAULT NULL,
  `consumed_runtime_run_id` varchar(64) DEFAULT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_by` bigint unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`queue_item_id`),
  UNIQUE KEY `uk_ai_session_queue_client_item` (`workspace_id`,`session_id`,`client_item_id`),
  UNIQUE KEY `uk_ai_session_queue_item_seq` (`workspace_id`,`session_id`,`item_seq`),
  KEY `idx_ai_session_queue_pending_order` (`workspace_id`,`session_id`,`status`,`position`,`item_seq`),
  KEY `idx_ai_session_queue_claim` (`status`,`claim_expires_at`),
  CONSTRAINT `fk_ai_session_queue_session` FOREIGN KEY (`session_id`) REFERENCES `ai_sessions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
