CREATE TABLE IF NOT EXISTS `ai_orchestration_plans` (
  `orchestration_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `parent_session_id` bigint unsigned NOT NULL,
  `status` varchar(32) NOT NULL,
  `phase` varchar(48) NOT NULL,
  `context_pack_digest` varchar(96) NOT NULL DEFAULT '',
  `synthesis_summary` longtext NOT NULL,
  `final_summary` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `claim_owner` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`orchestration_id`),
  UNIQUE KEY `uk_ai_orchestration_parent_run` (`workspace_id`,`parent_runtime_run_id`),
  KEY `idx_ai_orchestration_phase` (`workspace_id`,`status`,`phase`),
  KEY `idx_ai_orchestration_claim` (`status`,`claim_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_orchestration_context_packs` (
  `context_pack_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `orchestration_id` varchar(128) NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `source` varchar(64) NOT NULL,
  `trim_rules_json` longtext NOT NULL,
  `resource_versions_json` longtext NOT NULL,
  `token_estimate` bigint unsigned NOT NULL DEFAULT 0,
  `content_json` longtext NOT NULL,
  `digest` varchar(96) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`context_pack_id`),
  UNIQUE KEY `uk_ai_orchestration_context_digest` (`workspace_id`,`orchestration_id`,`digest`),
  KEY `idx_ai_orchestration_context_parent` (`workspace_id`,`parent_runtime_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `ai_orchestration_tasks` (
  `task_id` varchar(128) NOT NULL,
  `workspace_id` bigint unsigned NOT NULL,
  `orchestration_id` varchar(128) NOT NULL,
  `parent_runtime_run_id` varchar(64) NOT NULL,
  `task_seq` bigint unsigned NOT NULL,
  `task_kind` varchar(32) NOT NULL DEFAULT 'worker',
  `objective` longtext NOT NULL,
  `assigned_profile_id` bigint unsigned NOT NULL DEFAULT 0,
  `assigned_profile_version_id` bigint unsigned NOT NULL DEFAULT 0,
  `assigned_subagent_name` varchar(191) NOT NULL DEFAULT '',
  `mode` varchar(32) NOT NULL DEFAULT 'read_only',
  `dependency_ids_json` longtext NOT NULL,
  `context_pack_digest` varchar(96) NOT NULL DEFAULT '',
  `status` varchar(32) NOT NULL,
  `claim_owner` varchar(191) DEFAULT NULL,
  `claim_epoch` bigint unsigned NOT NULL DEFAULT 0,
  `claim_expires_at` datetime(3) DEFAULT NULL,
  `attempt` bigint unsigned NOT NULL DEFAULT 0,
  `child_run_link_id` varchar(128) DEFAULT NULL,
  `child_runtime_run_id` varchar(64) DEFAULT NULL,
  `result_summary` longtext NOT NULL,
  `artifact_refs_json` longtext NOT NULL,
  `error_code` varchar(96) DEFAULT NULL,
  `error_msg` text DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE KEY `uk_ai_orchestration_task_seq` (`workspace_id`,`orchestration_id`,`task_seq`),
  KEY `idx_ai_orchestration_task_status` (`workspace_id`,`orchestration_id`,`status`),
  KEY `idx_ai_orchestration_task_claim` (`status`,`claim_expires_at`),
  KEY `idx_ai_orchestration_task_parent` (`workspace_id`,`parent_runtime_run_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
